falcosecurity/falco-website

Makefile, netlify.toml
This PR adds a basic Netlify config for future use in the project.
=> Add Netlify config

_redirects, content/docs/event-sources/_index.md, content/docs/event-sources/dropped-events.md, content/docs/event-sources/kernel-module.md, content/docs/event-sources/kubernetes-audit.md, content/docs/event-sources/sample-events.md, content/docs/rules/_index.md, content/docs/source.md, data/config.yaml
The docs diverged from the wiki. Updating the docs on the site to match the wiki so we can shut down the wiki.
=> updates from wiki before removing wiki

content/docs/installation.md
Signed-off-by: Thorsten Schifferdecker <schifferdecker@b1-systems.de>
=> Fix broken link for event-sources/sample-events

content/docs/alerts/_index.md, content/docs/rules/supported-fields.md, data/config.yaml
Updates config options for new features in `0.15.0`. Also adding in page for all supported filter fields for rules.
=> update config options, add event fields page

content/docs/event-sources/dropped-events.md
Add link to blog post on CVE-2019-8339.
=> Add link to cve blog post

content/docs/source.md
Add some addl notes on how to use the falco-tester container.
=> Add test container notes

Makefile, content/docs/example.md, themes/falco-fresh/assets/style.sass, themes/falco-fresh/assets/toc.sass, themes/falco-fresh/layouts/partials/css.html, themes/falco-fresh/layouts/partials/docs/article.html
=> Add indented TOC

content/docs/source.md
=> restructure build from source documentation

content/docs/_index.md, content/docs/configuration.md, content/docs/running.md, themes/falco-fresh/layouts/shortcodes/latest.html
This PR is a first step in a general effort to polish up the docs and move them past the wiki stage.
=> Docs cleanup

content/docs/installation.md
Just some leftover refinements to the installation documentation.
=> docs(installation): refinements

content/docs/installation.md
From Minkube to Minikube
Signed-off-by: Guillaume Delaporte <guillaume.delaporte@gmail.com>
=> Fix typo in minikube title

config.yaml
Co-authored-by: Leonardo Di Donato <leodidonato@gmail.com>
=> new: bump falco version to 0.16.0

content/en/docs/source.md
Fixes #52
Refs https://github.com/falcosecurity/falco/pull/719 changes
=> docs: update the instruction to build from source

content/en/docs/rules/_index.md, themes/falco-fresh/assets/style.sass, themes/falco-fresh/layouts/partials/admonition.html, themes/falco-fresh/layouts/shortcodes/danger.html, themes/falco-fresh/layouts/shortcodes/info.html, themes/falco-fresh/layouts/shortcodes/requirement.html, themes/falco-fresh/layouts/shortcodes/success.html, themes/falco-fresh/layouts/shortcodes/warning.html
Relevant page:
https://deploy-preview-55--falcosecurity.netlify.com/docs/rules/
=> Rules doc cleanup

config.yaml
=> update: version 0.17.0

OWNERS
This PR introduces the OWNERS file.
(Prow has been already [setup](https://github.com/falcosecurity/test-infra/pull/57) for this repo).
Co-authored-by: Lorenzo Fontana <lo@linux.com>
=> new: owners file

.github/ISSUE_TEMPLATE/blog-content-request.md, .github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/cleanup.md, .github/ISSUE_TEMPLATE/content-request.md, .github/PULL_REQUEST_TEMPLATE.md
=> doc: issue and pull request template

config.yaml
/kind cleanup
NONE
We are releasing 0.17.1 this allows the website to reflect that.
=> update(falco-website): prepare for release v0.17.1

themes/falco-fresh/layouts/partials/docs/dashboard.html
/kind bug
/kind cleanup
To remove the duplicated entries
Fixes #84 
=> fix(themes/falco-fresh): filter out duplicated page sections

config.yaml, content/en/docs/grpc/_index.md, content/en/docs/grpc/client-go.md, content/en/docs/grpc/outputs.md, themes/falco-fresh/assets/fresh/partials/_footer.scss, themes/falco-fresh/assets/style.sass, themes/falco-fresh/layouts/shortcodes/githubcode.html
/kind bug
/kind design
NONE
Some flexbox black magic to stick the footer to the bottom, making the content of the page - also if empty - take all the space.
Fixes #80 
Screenshots into the issue linked above.
=> Stick the footer

content/en/docs/alerts/formatting.md, content/en/docs/event-sources/dropped-events.md, content/en/docs/event-sources/kernel-module.md, content/en/docs/grpc/_index.md, content/en/docs/grpc/client-go.md, content/en/docs/grpc/outputs.md, content/en/docs/rules/supported-fields.md, content/en/docs/running.md, content/en/docs/source.md, data/config.yaml, themes/falco-fresh/assets/bulma/sass/grid/columns.sass, themes/falco-fresh/assets/style.sass
/kind content
Adds documentation for the new gRPC server and outputs API.
It also fixes an issue in the layout enforcing the column has a max width of 100%.
Finally it ensures that Falco is capitalized.
Fixes #80 
**WIP**
=> grpc documentation

content/en/docs/grpc/_index.md, content/en/docs/grpc/client-go.md, content/en/docs/grpc/outputs.md
- Edited the doc for clarity and conformity. 
- Gave structure and added procedure
- Removed the highlighter as it's not displaying as expected on Github. Replaced with block code.
> /kind bug
> /kind design
> /area blog
Fixes #
=> Edited gRPC Doc for Clarity and Structure

content/en/docs/grpc/_index.md, content/en/docs/grpc/client-go.md, content/en/docs/grpc/outputs.md
=> fix: restore highlights for grpc

.gitignore, content/en/docs/_index.md, content/en/docs/source.md
Just clarifying the difference between `libscap`, `libsinsp` and `sysdig` as compared to Falco.
> /kind bug
/kind cleanup
> /kind design
> /area blog
Clarify language - these entities are confusing
Fixes #94 
=> Improving OSS Readability

content/en/blog/cloud-native-security-hub.md
> /kind bug
> /kind design
/kind content
> /area blog
Fixes #
=> Blog for security hub

content/en/docs/_index.md, content/zh/docs/_index.md
/kind bug
Fixes broken link to Falco configuration page
No issue
=> fix: Fix broken configuration link

content/en/blog/cloud-native-security-hub.md
We had a meeting at the pool and would like to have an official proposal for falcoctl
This fixes the blog for Kubecon to point to the proposal instead of having it in the blog
> /kind bug
/kind cleanup
> /kind design
> /area blog
Point to the official issue instead of the blog
Fixes #
=> Point to the official proposal

content/en/blog/cloud-native-security-hub.md
> /kind bug
/kind cleanup
> /kind design
> /area blog
Adding more examples and changes for the blog
Fixes #
=> Hub blog 3

content/en/docs/alerts/_index.md
/kind content
This PR rewords the introduction for the "program output" section of the documentation. It is slightly less concise now, but readability has been improved. Also, an example was added for using `xargs` with program outputs. This is useful when the program to use does not read from `stdin`.
There are no issues associated with this PR!
=> Reword program output doc and add an example

content/en/blog/runtime-security.md
> /kind bug
> /kind design
/kind content
/area blog
Just a resource about my opinions on what `runtime security` is. 
Fixes #
=> Adding Runtime Security Blog

content/en/docs/installation.md
/kind content
You can install epel with yum without figuring out manually an rpm for that.
Fixes #
=> docs(installation): install EPEL with the built-in command

content/en/docs/source.md
/kind content
PR https://github.com/falcosecurity/falco/pull/968 changed the way Falco build bundles (most of its own) deps.
Documentation about how to build Falco needs to be updated.
Fixes #
=> update: build from source docs

themes/falco-fresh/assets/style.sass, themes/falco-fresh/assets/toc.sass, themes/falco-fresh/layouts/partials/docs/article.html
> /kind bug
> /kind design
> /area blog
Fixes #
=> Add sticky scroll for TOC

content/en/docs/event-sources/sample-events.md
https://github.com/falcosecurity/falco/pull/997 recently added support
for k8s audit rules to the event generator. This updates the docs to
reflect those changes.
> /kind bug
> /kind design
/kind content
> /area blog
Fixes #
Add docs for new k8s event generator.
=> Add docs for k8s event generator

config.yaml, themes/falco-fresh/layouts/partials/signup.html
- Now pointing to CNCF mailing list instead of sysdig.com
> /kind bug
/kind cleanup
> /kind design
> /area blog
Fixes #
=> Updating sign up

config.yaml, themes/falco-fresh/layouts/partials/signup.html
> /kind bug
> /kind design
> /area blog
Right now the HTML tags from the CNCF list page was autofocusing on the mailing list - fixing this so the page loads correctly 
Fixes #
=> Fix autofocus

content/en/docs/changelog.md, themes/falco-fresh/assets/style.sass, themes/falco-fresh/layouts/shortcodes/changelog.html
This PR adds version links to the changelog and updates the aesthetic a bit.
Preview available here:
https://deploy-preview-128--falcosecurity.netlify.com/docs/changelog/
=> Update Changelog aesthetic

data/config.yaml
/kind content
> /area blog
Fixes #
=> new: document grpc flags

content/en/docs/source.md
fix Word Error
> /kind bug
Fixes #
=> fix: wrong word for docs/source.md

config.yaml
/kind bug
Fixes the link of the "Get started" button in the homepage.
Fixes #136
None :)
=> fix: get started button anchor

content/en/docs/event-sources/kubernetes-audit.md
Edited content to fix issues such as:
* to replace K8s to Kubernetes
* add bullet points for clarity and task orientation
* cut words for brevity
* change passive to active voice 
radhika.dwaraka@gmail.com
=> edited the content for clarity and completeness

content/en/docs/event-sources/dropped-events.md
Signed-off-by: Radhika Puthiyetath <radhika.dwaraka@gmail.com>
* Fixed the broken link to configuration.md file
* Edited for clarity
=> edited the content to give clarity and fix broken links

content/en/docs/installation.md
related to: https://github.com/falcosecurity/falco/pull/1050
/kind content
Documenting the new `FALCO_BPF_PROBE` as described here: https://github.com/falcosecurity/falco/pull/1050
=> new: document the new FALCO_BPF_PROBE variable

content/en/blog/falco-0-20-0.md
/kind cleanup
/kind content
/area blog
Fixes a typo.
NONE
=> chore(content/en/blog): typo

config.yaml, content/en/docs/installation.md, content/en/docs/running.md, content/en/docs/source.md
> /kind bug
> /kind design
/kind content
> /area blog
Fixed Falco image tag in the documentation
=> Fix image tag version in documentation

content/en/docs/event-sources/dropped-events.md
/kind bug
/kind content
Fixes a link to Falco configuration docs page.
Fixes #
=> fix(content/en/docs/event-sources): correct link to config

content/en/docs/grpc/_index.md, content/en/docs/grpc/client-python.md
Signed-off-by: Mattia Meleleo <melmat@tuta.io>
/kind cleanup
/kind content
Adds Python client documentation
Fixes https://github.com/falcosecurity/falco-website/issues/126
=> new(content/en/docs): add Python client docs

config.yaml, content/zh/docs/installation.md, themes/falco-fresh/layouts/partials/hero-body.html
Signed-off-by: nevermosby <legendarilylwq@gmail.com>
This PR provides the Chinese translation for falco.org/zh/docs/installation page.
This PR is related to #43 .
N/A
=> translate docs/installation into Chinese

content/en/blog/minikube-falco-kernel-module.md
/kind content
/area blog
Fixes #
=> new(blog): add content for minikube support for Falco

content/en/docs/running.md
> /kind bug
> /kind design
/kind content
> /area blog
This PR adds instructions on how to properly run Falco in a Kind cluster.
Fixes #
=> new(content/en/docs): running Falco in a Kind cluster

content/en/docs/source.md
=> doc: update regression test section to use Python 3

content/en/docs/event-sources/sample-events.md
> /kind bug
/kind cleanup
> /kind design
/kind content
> /area blog
Fixes #
=> docs: updating docker run command for sample events

content/en/blog/falco-kind-prometheus-grafana.md
> /kind bug
> /kind design
/kind content
/area blog
Fixes #
@kris-nova Thank you for helping me out!
=> new(blog): add content for Falco on Kind with Prometheus and Grafana

themes/falco-fresh/layouts/partials/language-toggler.html, themes/falco-fresh/layouts/partials/navbar.html
This PR adds a language toggler that can accommodate > 2 languages
=> Add language toggler

OWNERS
Just adding myself as owner/reviewer.
> /kind bug
> /kind design
> /area blog
Fixes #
=> new: owner (leogr)

content/jp/docs/_index.md, content/jp/docs/configuration.md, content/jp/docs/examples.md, content/jp/docs/installation.md, content/jp/docs/running.md
/kind bug
/kind content
/kind transalation
Needed fix for URL out of link.
Translated running.md to Japanese.
Translated examples.md to Japanese
Translated configuration.md to Japanese
=> Fixed URL out of link

themes/falco-fresh/layouts/blog/section.rss.xml
Signed-off-by: nevermosby <legendarilylwq@gmail.com>
/kind bug
/area blog
This PR is aim to fix issue #79 ,  thus, the rss feed can export full content of blog.
Fixes #79  
N/A
=> fix rss feed to export full content of blog

content/jp/docs/_index.md
/kind bug
/kind cleanup
/kind content
delete some blank and fix URL link to Japanese documents
/leodido 
/fntlnz
=> delete some blank and fix URL link to Japanese documents

i18n/en.yaml, i18n/jp.yaml, i18n/zh.yaml, themes/falco-fresh/layouts/partials/footer.html
=> Update copyright footer text

content/en/blog/falco-0-22-x.md
Co-authored-by: Lorenzo Fontana <lo@linux.com>
/kind content
/area blog
Blog post for Falco 0.22.x serie release!
NONE
=> new(content/en/blog): Falco 0.22.x blog post

content/en/docs/event-sources/sample-events.md
> /kind bug
> /kind design
/kind content
> /area blog
Fixes #185 
I will open another PR for https://github.com/falcosecurity/falco-website/issues/185#issuecomment-617876795
=> update(content/en/docs/events-source): new event generator

content/jp/docs/event-sources/sample-events.md
/kind content
English sample-events.md updated. So, Japanese document updated too.
=> updated sample-events.md

content/en/docs/event-sources/kernel-module.md, content/en/docs/installation.md
/kind content
Refers to #191 - jp and cn translation needs to be done.
=> update(content): update driver load documentation with the new variables

content/en/blog/falco-0-23-0.md
/kind content
/area blog
Fixes #
=> new(content/en/blog): release post for 0.23.0

content/en/docs/installation.md
Updating language in install notice to be more user friendly
> /kind bug
> /kind design
> /area blog
Fixes #
=> feat(docs): Updating install info

themes/falco-fresh/layouts/partials/css.html, themes/falco-fresh/layouts/partials/footer.html, themes/falco-fresh/layouts/partials/logos.html, themes/falco-fresh/layouts/partials/resources.html, themes/falco-fresh/layouts/partials/runtime.html, themes/falco-fresh/layouts/partials/signup.html, themes/falco-fresh/layouts/partials/whyfalco.html, themes/falco-fresh/static/css/custom.css
> /kind bug
/kind cleanup
/kind design
/kind content
> /area blog
Cosmetic changes of the site, 
including structuring the Develop section
Highligth parts of text
Added a font fade effect to "orginally created by", (migth update this later, if there's a better way to make the section better)
Made footer fluid, and moved around the text so it would look more aesthetically.
Made logos section fluid, and made so that the images are not round!
And just small formating of source code.
```
(
`-`-.
'( @ >
_) (
/    )
/_,'  / 
\  / …
```
=> small adjustment to make the site feel more finished, and small cosmetic changes.

content/en/docs/third-party.md
> /kind bug
> /kind design
> /area blog
Fixes #
=> feat(docs): Update helm chart

content/en/docs/source.md
=> docs(content/source): update link for python dependencies

content/en/docs/grpc/_index.md, data/en/config.yaml
/kind content
Related to the changes to Falco:
- https://github.com/falcosecurity/client-go/pull/43
Fixes #
=> docs: gRPC unix socket usage

content/en/blog/minikube-falco-kernel-module.md
re: https://github.com/falcosecurity/charts/issues/13
/kind cleanup
> /area blog
Helm Chart Repo changes
Fixes #
=> Minor docs updates: chart repo

content/en/blog/falco-kind-prometheus-grafana.md
Updating our helm instructions after helm chart changes
re: https://github.com/falcosecurity/charts/issues/13
/kind cleanup
/area blog
Fixes after Helm Chart work
Fixes #
=> fix(blog): Update helm instructions

content/en/docs/third-party.md
> /kind bug
> /kind design
/kind content
> /area blog
Fixes #214 
=> docs(content): add note when installing Falco with Helm on GKE

themes/falco-fresh/assets/fresh/partials/_sections.scss, themes/falco-fresh/layouts/index.html, themes/falco-fresh/layouts/partials/announce.html
The Falco Project takes a stand against racism.
> /kind bug
> /kind design
/kind content
> /area blog
Fixes #
=> feat(black-lives-mattter): Adding header to falco.org

content/en/docs/grpc/_index.md, content/en/docs/grpc/client-go.md, content/en/docs/grpc/client-py.md, content/en/docs/grpc/outputs.md, content/en/docs/grpc/version.md
/kind content
Updates the gRPC documentation to support the upcoming changes introduced by PR https://github.com/falcosecurity/falco/pull/1241
It requires https://github.com/falcosecurity/falco/pull/1241 to be merged to build correctly.
=> update gRPC docs to the new gRPC APIs

content/en/docs/running.md, themes/falco-fresh/assets/bulma/sass/utilities/initial-variables.sass, themes/falco-fresh/assets/style.sass, themes/falco-fresh/layouts/partials/navbar.html
Adds an explaination around some common issues Falco users experience. 
BONUS: Fix coloring to reflect Falco branding.
This would not have been possible with my CSS skills alone. Thanks @leodido @leogr 
/kind content
Related to:
- https://github.com/falcosecurity/falco/issues/1253
- https://github.com/falcosecurity/falco/issues/1299
Fixes #
=> docs: add caveats on running least privileged

content/en/blog/detect-cve-2020-8557.md
Signed-off-by: kaizhe <derek0405@gmail.com>
> /kind bug
> /kind design
/kind content
/area blog
Fixes #
=> add blog detecting cve-2020-8557 using falco

content/en/docs/_index.md, content/en/docs/event-sources/drivers.md, content/en/docs/running.md, themes/falco-fresh/static/css/custom.css
/kind design
/kind content
Documenting userspace instrumentation added in https://github.com/falcosecurity/falco/pull/1195
This is also area/design because I put back bullet lists. More explaination in the commit message.
Fixes #228 
/honk
=> Userspace instrumentation docs

content/en/docs/installation.md
/kind content
We encountered some minor problems while manually testing the packages installation procedure during the pre-release checklist.
This PR improves the installation procedure in order to solve those issues.
Fixes #
Still WIP.
/cc @leodido
=> fix(content/en/docs): correct installation instructions for CentOS

content/en/docs/source.md, content/jp/docs/source.md
/kind content
This PR updates the docs as per https://github.com/falcosecurity/falco/pull/1313
Refs https://github.com/falcosecurity/falco/issues/1312
/hold
Hold this PR until https://github.com/falcosecurity/falco/pull/1313 is merged into Falco.
=> update instructions to run integration test locally

content/en/docs/event-sources/drivers.md
/kind content
fix small typo on website docs
=> fix small typo

content/en/docs/source.md
=> docs: ubuntu 18.04 specific instructions

content/en/blog/falco-0-25-0.md
Co-Authored-By: Leonardo Grasso <me@leonardograsso.com
/kind content
Fixes #
=> content: blog for 0.25.0

content/en/docs/source.md
> /kind bug
/kind cleanup
> /kind design
/kind content
> /area blog
Fixes #
Still need to fix it in other langs.
=> fix(content): falco-probe terminology is not used anymore

content/en/blog/falco-0-23-0.md, content/en/docs/download.md, content/jp/docs/download.md
/kind bug
/kind content
The container image `falco-driver-loader` and `falco` description should be _falco-driver-loader_ and _falco-driver-loader included_.
Fixes #
=> fix: correct container image naming

content/en/docs/source.md
Co-authored-by: Leonardo Di Donato <leodidonato@gmail.com>
Co-authored-by: Lorenzo Fontana <lo@linux.com>
/kind content
See :point_right: https://github.com/falcosecurity/falco/pull/1377
And
/hold
until it gets merged
Fixes #
=> update(content/en/docs): add Alpine section for the statically-linked build

content/en/docs/alerts/_index.md
/kind content
Fixes #241 
/cc @fntlnz
=> update(content): add gRPC output to alerts list

content/en/blog/falco-kind-prometheus-grafana.md
/kind bug
/area blog
Just some old links and examples that need to be fixed in the "Falco on Kind with Prometheus and Grafana" blog post.
Fixes #
=> fix(blog): outdated links and examples in "Falco on Kind"

content/en/docs/examples.md
Hello,
As said in title : fix 1 typo in examples.md
=> examples.md : fix 1 typo

config.yaml, content/en/videos/_index.md, content/jp/videos/_index.md, content/zh/videos/_index.md, themes/falco-fresh/assets/fresh/partials/_cards.scss, themes/falco-fresh/layouts/index.html, themes/falco-fresh/layouts/partials/featuredvideo.html, themes/falco-fresh/layouts/partials/navbar.html, themes/falco-fresh/layouts/partials/resources.html, themes/falco-fresh/layouts/partials/videos/hero.html, themes/falco-fresh/layouts/partials/videos/video-list.html, themes/falco-fresh/layouts/videos/section.html
As discussed in the last community call [here](https://github.com/falcosecurity/community/blob/master/meeting-notes/2020-09-16.md#this-week-highlights) I'm following up with some improvements to the Falco website, namely:
- Videos can be updated using `config.yaml`
- Featured video in the home page is the most recent one in `config.yaml`
- Each language has its own video list
- Bonus: CSS fixes
*Screenshots*
Featured video in home page:
Video list: 
Fixes #
=> Videos on the Falco website and layout improvements

content/en/blog/choosing-a-driver.md
Adding a blog to help with choosing a driver
Signed-off-by: Kris Nóva <kris@nivenly.com>
> /kind bug
> /kind design
> /area blog
Fixes #
=> feat(blog): Choosing a driver

.github/PULL_REQUEST_TEMPLATE.md, config.yaml
/kind content
/area videos
Adds the video recording of my talk at RomHack2020 on Sunday 27th Sept. 2020 in Rome.
NONE
=> Adding Leo's talk at RomHack2020 in the videos list

config.yaml, content/en/blog/falco-0-26-1.md, content/en/docs/installation.md, content/ko/videos/_index.md
/kind content
/area blog
A blog post for Falco 0.26.1 release.
Fixes the installation of binary release.
Fixes the korean website structure.
NONE
=> Release/0.26.1 + installation fixes + korean website fixes

config.yaml, content/ko/docs/download.md
/kind content
- Translate Download page(`/docs/download`) to Korean.
- Update main page(`config.yaml`) video part.
.
---
cc @jmyung
=> Translate Download page to Korean

content/en/docs/source.md
/kind content
Add openSUSE on build Falco from source and fix typo.
Fixes #
=> update(content/en/docs): add openSUSE on build Falco from source

content/ko/docs/examples.md
Translate docs/examples in Korean
No korean doc for docs/examples
/Closes #269 
@futureCreator
=> Translate docs/examples in Korean

content/ko/docs/psp-support/_index.md
/kind content
Translate PSP Support page(`/docs/psp-support`) to Korean.
Fixes #271 
@jmyung
=> Translate docs/psp-support page into Korean

content/en/docs/source.md
=> docs: add libyaml-cpp-dev to ubuntu without bundled deps

content/ko/docs/installation.md
/kind content
Translate Installation page(`/docs/installation`) to Korean.
Fixes #275 
@jmyung
=> Translate docs/installation page into Korean

content/ko/docs/source.md
Signed-off-by: Jerry Park <jaehwa@gmail.com>
/kind content
Translate docs/source into Korean.
Fixes #278 
@jmyung
=> Translate docs/source into Korean

content/ko/docs/configuration.md, data/ko/config.yaml
/kind content
Translate docs/configuration into Korean
Fixes #278 
@jmyung
=> Translate docs/configuration into Korean

content/en/docs/installation.md
/kind cleanup
Correct typos 'into into' 👉 'into' in `docs/installation` page.
Fixes #299 
=> Typo correction

content/ko/docs/third-party.md
/kind content
Translate third-party page(`/docs/third-party`) into Korean.
Fixes #276 
=> Translate docs/third-party into Korean

content/en/blog/falco-0-26-1.md, content/en/docs/installation.md, content/en/docs/source.md
/kind content
Support installation Falco at openSUSE
Fixes #
=> update(content/en/docs): add installation at openSUSE

data/en/config.yaml
/kind bug
/kind cleanup
/kind content
The gRPC config description was not updated w.r.t the unix socket binding type.
Fixes #
=> update(data/en): correct and update gRPC config description

content/zh/docs/installation.md
The current installation may not work, need to update helm repo
Fixes #
=> update(data/zh): update helm installation

content/en/blog/falco-0-26-2.md
/kind content
/area blog
Fixes #
=> new(content/en/blog): announcement for 0.26.2

config.yaml, content/en/blog/falco-0-26-2.md
/kind content
/area blog
Fixes #
=> fix(content/en/blog): typo in release blog and version in config.yaml

content/en/blog/falco-0-26-2.md
Reported-By: Leonardo Grasso <me@leonardograsso.com>
/kind content
/area blog
Fixes #
=> fix(content/en/blog): add link to infra wg

content/en/docs/rules/_index.md
/kind content
- Documents that the rule configuration file order matters
- Documents how default rules can be disabled
Fixes https://github.com/falcosecurity/falco/issues/1469
/cc @leogr 
Thanks & regards,
Philip
=> Added rule order and disable rule documentation

content/en/blog/extend-falco-outputs-with-falcosidekick.md
> /kind bug
> /kind design
/kind content
/area blog
> /area videos
Someone noticed me I wrote a wrong configuration for `falco` in my article, here the fix.
N/A
Fixes #
=> fix wrong config for falco

content/en/docs/event-sources/kubernetes-audit.md
> /kind bug
/kind cleanup
> /kind design
> /area blog
> /area videos
Fixes # https://github.com/falcosecurity/falco-website/issues/159
=> update (content/en) Updated the example for consistency

content/en/docs/grpc/client-go.md
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> update (content/en): Fixed a broken link and minor copy edits

content/en/docs/_index.md
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Fixes #
Rewrote and edited the content with a view to brevity, clarity, and readability
=> [update] Restructure the content on _index.md

OWNERS
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
- Work on the information architecture based on user persona
- Reviewing Documentation changes and messaging
- Help with the Documentation working group to do improvements for the new website
=> [new] Applying for the role of a maintainer

config.yaml
> /kind bug
/kind cleanup
> /kind design
> /area blog
> /area videos
Fixes #
=> [update] The links in the buttons to the new location

content/en/docs/getting-started/third-party.md
=> update(content/en): add docker in kind config

config.yaml
> /kind bug
/kind cleanup
> /kind design
> /area blog
> /area videos
Fixes #
=> [update] reworded the configure button in the main page

content/en/blog/security-boundaries-with-systemd-and-kubernetes.md
Signed-off-by: Kris Nóva <kris@nivenly.com>
> /kind bug
> /kind design
/kind content
/area blog
> /area videos
Fixes #
had this question a lot recently - just adding my way of doing things if we are interested in accepting
=> feat(blog): adding systemd blog

content/en/blog/falco-2020.md
/kind content
/area blog
During my personal yearly self-review, I started reflecting back on Falco in 2020.
The number of things I remembered was so big that I had to separate the artifact in another blog post that is now suitable for the Falco blog, imho.
NONE
=> Falco in 2020 (blog post)

content/en/blog/falco-wsl2-custom-kernel.md
/kind content
/area blog
This PR adds a blog post explaining the process to get the Falco kernel module on WSL2.
It should open the doors to a part of the Windows community and let them "relate" to the overall Falco project and documentation.
N/A
While the content is there, the "form" might be too light or "different" from the rest of the documentation. I really wrote it as a guest blog post, so please feel free to adapt the form.
The conclusion also points at using Falco with the preferred Kubernetes distro, however if you have better follow-up blogs or articles then it would be great to add …
=> [Blog] Create falco-wsl2-custom-kernel.md

config.yaml
Signed-off-by: Naoki Oketani <okepy.naoki@gmail.com>
/kind cleanup
Fix a typo.
Fixes #
=> fix(config.yaml): typo of Serverless

config.yaml, content/jp/blog/_index.md, content/jp/blog/falco-2020.md
/kind content
/area blog
Translated blog "Falco in 2020" to Japanese.
=> Translated blog falco-2020

content/en/blog/falcosidekick-2020.md
/kind bug
> /kind design
/area blog
> /area videos
Fix a typo in a link.
Fixes #
=> fix typo in blog post falcosidekick-2.20.0

content/en/blog/intro-k8s-security-monitoring.md
Signed-off-by: Frederick <frederickfrnnd@gmail.com>
/kind content
> /area blog
Fixes a typo in the blog which I contributed to earlier.
Fixes #
=> blog: Removed typo from intro security monitoring blog

config.toml
=> update: fix analytics

content/en/docs/contribute/contributor-of-the-month.md
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Updated the contributor of the month page
Fixes #
Here's the preview: https://deploy-preview-358--falcosecurity.netlify.app/docs/contribute/contributor-of-the-month/
=> [update] the contributor of the month page

content/ja/docs/grpc/_index.md
Signed-off-by: Naoki Oketani <okepy.naoki@gmail.com>
/kind cleanup
There is a link in English version, but not in Japanese version.
Fixes #349
=> fix: add a link to the Japanese version along with the English version

config.toml
=> fix: mailing list url

README.md
/kind cleanup
README.md contains a broken link and outdated document in Japanese section.
Fixes #362
=> fix: update README.md according to changes in the directory structure

content/en/blog/exceptions.md
The content is a mix of the docs and the original proposal.
> /kind bug
> /kind design
/kind content
/area blog
> /area videos
Fixes #
=> Add blog post for exceptions

README.md
Signed-off-by: Naoki Oketani <okepy.naoki@gmail.com>
/kind cleanup
README.md contains 4 broken links to config.yaml.
Fixes #361 
=> fix: update broken links in README.md

content/en/blog/exceptions.md
/kind content
/area blog
To avoid any confusion in readers, it's probably better to specify the first Falco development version that includes support for this new feature (Falco rules exceptions).
NONE
Proposed the same [for the docs page](https://github.com/falcosecurity/falco-website/pull/345#issuecomment-763606639).
=> Clarify the first Falco version that includes support for the exceptions feature

config.toml
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> [Update] fixed the link to Falco - calendar

content/ja/docs/running.md
Signed-off-by: Saintmalik <msalawu5@gmail.com>
Easy navigation and easy reading for others
/kind
=> Fix broken url in docs

content/ja/blog/falco-wsl2-custom-kernel.md
/kind content
/area blog
Translated to Japanese
=> Translated to Japanese: Falco on WSL2 with a custom kernel

config.toml
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> Added SHA256 variable

content/ja/blog/intro-k8s-security-monitoring.md
/kind content
/area blog
Translated for Japanese
=> Translated to Japanese: An Introduction to Kubernetes Security using Falco

content/en/docs/rules/_index.md
See also: https://github.com/falcosecurity/falco/issues/1537
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
See https://github.com/falcosecurity/falco/issues/1537
Fixes #
/cc @Rajakavitha1
=> docs(content/en/docs/rules): add warning for `Via Custom Rule Definion` section

content/en/docs/rules/_index.md, content/en/docs/rules/exceptions.md
Add docs that note the new exceptions fields and a standalone page that
describes how exceptions work in more detail. Text borrowed heavily from
the original exceptions proposal.
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Fixes #
=> Add docs for exceptions support

content/ja/blog/falcosidekick-2020.md, content/ja/blog/falcosidekick-kubeless.md
/kind content
/area blog
Translated to Japanese
=> Translated to Japanese: 2 Falcosidekick blogs

content/en/docs/getting-started/source.md
/kind content
Install kernel-header for Arch Linux.
Fixes #
=> Install kernel headers for Arch Linux

content/en/docs/alerts/_index.md, content/ja/docs/alerts/_index.md
Signed-off-by: Naoki Oketani <okepy.naoki@gmail.com>
/kind cleanup
Falco Alerts: an example logrotate config is a broken link.
Fixes #369
=> chore: fix broken links

content/ja/blog/exceptions.md, content/ja/blog/falco-0-27-0.md, content/ja/blog/falco-performance-testing.md, content/ja/blog/falcosidekick-2020.md, content/ja/blog/falcosidekick-kubeless.md
/kind content
/area blog
Useful for Japanese
Special notes for your reviewer:
=> Translated to JA Falco 0.27.0 a.k.a. "The happy 2021 release"

content/en/docs/getting-started/third-party/learning.md
/kind cleanup
Improves the wonderful documentation
Fixes #399 
=> Improve getting started minikube docs

content/en/blog/contribution-drivers-kmod-ebpf-libraries.md
/kind content
/area blog
Fixes #
/cc @leodido
=> update(content/en/blog): add CNCF blog post link

config.toml, release.md
/kind content
It switches the Falco website to Falco 0.28.0 version.
NONE
/hold
=> new: switch website to Falco 0.28 version

content/en/blog/falco-0-28-0.md, content/en/blog/falco-0-28-1.md, content/en/docs/getting-started/running.md
/kind content
/area blog
Blog post for Falco 0.28 release.
NONE
/hold
until release is completed.
=> new(content/en/blog): Falco 0.28.0 blogpost

content/en/docs/getting-started/upgrade.md
/kind content
Add upgrade guide for openSUSE.
Fixes #
=> Add upgrade guide for openSUSE

content/en/blog/extend-falco-outputs-with-falcosidekick.md
Signed-off-by: Dan POP <dan.papandrea@sysdig.com>
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> added Get Involved details

content/en/docs/contribute/contributor-of-the-month.md
Signed-off-by: Dan POP <dan.papandrea@sysdig.com>
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> Update for April 2021

content/en/blog/falcosidekick-openfaas.md
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> [Blog] OpenFaaS output type blog post ready

content/en/blog/falcosidekick-openfaas.md
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
> /kind bug
> /area blog
Fixes #
=> little fixes about openfaas output type blog post

content/en/blog/falcosidekick-reponse-engine-part-1-kubeless.md, content/en/blog/falcosidekick-reponse-engine-part-2-openfass.md, package-lock.json
> /kind bug
> /kind design
/kind content
/area blog
> /area videos
Rename and join blog posts about kubernetes response engine as a serie
Fixes #
=> rename and join posts as a serie for kubernetes response engine

content/en/blog/falco-0-28-1.md
/kind content
/area blog
blog: add blog for Falco release 0.28.1
related to https://github.com/falcosecurity/falco/issues/1635
=> blog: add blog for Falco release 0.28.1

content/en/docs/getting-started/source.md
Remove repeated text on  "Load latest falco kernel module"
=> Remove repeated text

content/en/blog/falcosidekick-reponse-engine-part-4-tekton.md
/kind content
/area blog
Showcase Tekton and falco demo building a Kubernetes Response Engine
=> Kubernetes Response Engine, Part 4: Tekton

content/en/blog/falcosidekick-reponse-engine-part-1-kubeless.md, content/en/blog/falcosidekick-reponse-engine-part-2-openfass.md, content/en/blog/falcosidekick-reponse-engine-part-3-knative.md
+ fix date for native post
> /kind bug
> /kind design
/kind content
/area blog
> /area videos
Set same headers for all posts about Response Engine
Fix date of posts for Reponse engine with Knative
Fixes #
=> set same header for all posts about response engine

content/en/docs/rules/_index.md
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
just a little typo
Fixes #
=> docs_fix(little typo)

content/en/blog/falcosidekick-reponse-engine-part-4-tekton.md
Signed-off-by: Sruthy Santhosh <sruthysanthosh002@gmail.com>
/kind bug
> /kind design
/kind content
/area blog
> /area videos
Fixes #
=> Fix typos in the Blog

package-lock.json, package.json
/kind bug
> /kind design
> /area blog
> /area videos
Upgrade some dependencies with known security vulnerabilities.
Fixes #
=> build: upgrade deps

content/en/docs/event-sources/sample-events.md
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> Fix link to events generator project

content/en/blog/falco-i18n.md
Signed-off-by: radhikapc <radhika.dwaraka@gmail.com>
> /kind bug
> /kind design
/area blog
> /area videos
This document helps you familiarize yourself with the i18n workflow followed by the Falco Community.
Fixes #
=> blog for i18n process

content/en/blog/falco-i18n.md
Signed-off-by: radhikapc <radhika.dwaraka@gmail.com>
> /kind bug
> /kind design
/area blog
> /area videos
Fixes #
Changed a section heading to a crispier one to enhance readability
=> changed a section heading to a crispy one

content/en/blog/falco-i18n.md
Signed-off-by: radhikapc <radhika.dwaraka@gmail.com>
> /kind bug
> /kind design
/area blog
> /area videos
Language and style edit to improve readability.
Fixes #
=> Language and style edit to improve readability

content/en/docs/rules/exceptions.md
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Several changes to improve the exceptions docs:
- Show the equivalent rule condition snippet earlier and drop the
"Syntatic sugar" section.
- More clearly state how fields/comps/relate
- Add a section Exception Syntax Shortcuts for alternate representations.
Fixes #
=> Revamp exceptions docs

.github/PULL_REQUEST_TEMPLATE.md, config.toml, content/en/docs/contribute/_index.md
/kind bug
> /kind design
/kind content
> /area blog
> /area videos
This fixes some links and provides a path from the docs to the contribution guide
Fixes #
=> Fixing documentation links

content/en/blog/falco-0-29-0.md
Signed-off-by: maxgio92 <massimiliano.giovagnoli.1992@gmail.com>
/kind content
/area blog
Blog post for Falco 0.29.0 release.
NONE
/hold
=> new(content/en/blog): 0.29.0 release

content/en/blog/falcosidekick-reponse-engine-part-1-kubeless.md
Signed-off-by: Sruthy Santhosh <sruthysanthosh002@gmail.com>
> /kind bug
> /kind design
/kind content
/area blog
> /area videos
Fixes #
=> language review for readablity

content/en/docs/getting-started/running.md
Signed-off-by: Thomas Spear <tspear@conquestcyber.com>
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Fixes #459  
=> Add examples of running falco-no-driver and falco-driver-loader in fully privileged mode and reasons why one might want to

config.toml
Signed-off-by: Atarax665 <manasgmishra@gmail.com>
/kind cleanup
> /area blog
> /area videos
Updated the correct URL of GitLab in config.toml
Fixes #469 
=> Updated GitLab URL

content/en/blog/falcosidekick-reponse-engine-part-7-cloud-functions.md
Signed-off-by: Furkan <furkan.turkal@trendyol.com>
/kind bug
/kind content
/area blog
=> hotfix: fix image name typo for cloud func blog

content/en/blog/falcosidekick-reponse-engine-part-1-kubeless.md, content/en/blog/falcosidekick-reponse-engine-part-2-openfass.md, content/en/blog/falcosidekick-reponse-engine-part-3-knative.md, content/en/blog/falcosidekick-reponse-engine-part-4-tekton.md, content/en/blog/falcosidekick-reponse-engine-part-5-argo.md, content/en/blog/falcosidekick-reponse-engine-part-6-cloud-run.md, content/en/blog/falcosidekick-reponse-engine-part-7-cloud-functions.md
> /kind bug
/kind cleanup
> /kind design
/area blog
> /area videos
We now have a nice list of posts about creation of a kubernetes response engine, this PR is only to reference all articles in all posts for helping readers.
Fixes #
=> set same header with list of all posts in serie about response engine

content/en/blog/falcosidekick-response-engine-part-8-fluxv2.md
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> fix the date of the KRE with flux v2 blog post

content/en/blog/falco-detect-malicious-behavior-through-audit-logs.md, content/en/blog/falcosidekick-response-engine-part-1-kubeless.md, content/en/blog/falcosidekick-response-engine-part-2-openfass.md, content/en/blog/falcosidekick-response-engine-part-3-knative.md, content/en/blog/falcosidekick-response-engine-part-4-tekton.md, content/en/blog/falcosidekick-response-engine-part-5-argo.md, content/en/blog/falcosidekick-response-engine-part-6-cloud-run.md, content/en/blog/falcosidekick-response-engine-part-7-cloud-functions.md, content/en/blog/falcosidekick-response-engine-part-8-fluxv2.md
/kind content
/area blog
Fixes file name and slug.
Signed-off-by: Gaurav Gahlot <gauravgahlot0107@gmail.com>
=> Fix reponse -> response

content/en/docs/getting-started/installation.md
Signed-off-by: lucklypse <lucklypse@gmail.com>
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Add a performance note to the eBPF probe. If jit is not available Falco's performance would be very degraded so warn the user about this at install time.
Fixes #494
=> docs: add performance note for eBPF in install instructions

config.toml
> /kind bug
/kind cleanup
> /kind design
> /area blog
> /area videos
Fixes #
=> update: switching to Falco 0.30.0

layouts/partials/labs.html
/kind bug
/kind content
This PR fixes a typo: `thread` is corrected to `threat`.
None.
None.
Signed-off-by: Alejandro Villanueva <alejandro@alejandrovillanueva.eu>
=> fix: spelling

content/en/docs/getting-started/source.md
Signed-off-by: Sachin Kumar Singh <sachinkumarsingh092@gmail.com>
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
During building Falco in Arch Linux from scratch, we found out that `linux-headers` are required for the proper building of Falco binaries.
Fixes #
=> fix: Improve build for source dependencies for Arch Linux

content/en/blog/falco-wsl2-custom-kernel.md
https://github.com/microsoft/WSL2-Linux-Kernel/blob/7015d6023d60b29c3be4c6a398bed923b48b4341/Microsoft/config-wsl is html format, switch to use raw text link: https://raw.githubusercontent.com/microsoft/WSL2-Linux-Kernel/7015d6023d60b29c3be4c6a398bed923b48b4341/Microsoft/config-wsl to fix kernel config
/kind bug
/area blog
Fix wsl custom kernel blog
Fixes #
=> fix(blog): update Microsoft/config-wsl github link

content/en/docs/event-sources/kubernetes-audit.md
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Fixes #
=> fix: link to auditing with falco

config.toml
Signed-off-by: Jason Dellaluce <jasondellaluce@gmail.com>
/kind cleanup
This bumps the Falco version to `v0.30.0`, which has not been updated after the latest release.
=> chore: update falco version in config.toml to v0.30.0

content/en/docs/rules/_index.md
Signed-off-by: Jason Dellaluce <jasondellaluce@gmail.com>
/kind content
This updates the rule docs to follow up the changes introduced in https://github.com/falcosecurity/falco/pull/1775.
=> doc(rules): document enabled-only rule definitions

config.toml
Signed-off-by: Jason Dellaluce <jasondellaluce@gmail.com>
/kind cleanup
This updates `config.toml` for the new Falco 0.31.0 release, as described in the [release process](https://github.com/falcosecurity/falco-website/blob/master/release.md#bump-the-version-on-the-current-website) of this repository.
=> update(config.toml): update version info for 0.30 and append entry for 0.31

content/en/blog/announcing_plugins_and_cloud_security_with_falco.md
> /kind bug
> /kind design
/kind content
/area blog
> /area videos
This blog post talks about the newly released plugin infrastructure and how Falco is expanding into the domain of cloud security.
Fixes #
=> new blog post: Announcing Plugins and Cloud Security with Falco

content/en/blog/extend-falco-inputs-with-a-plugin-the-basics.md
Signed-off-by: Issif <issif+github@gadz.org>
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Blog post: `Extend Falco inputs by creating a Plugin: the basics`
Fixes #
=> Extend Falco inputs by creating a Plugin: the basics

content/en/docs/getting-started/running.md
Signed-off-by: tonghuaroot <tonghuaroot@gmail.com>
Update userspace instrumentation Link.
> /kind bug
The original content is
```
Are you looking for userspace instrumentation? Please see [this page](https://falco.org/docs/event-sources/drivers/).
```
Combined with the content of the document, in the hyperlinks section, I have provided minor adjustments that can directly navigate to the intended content.
```
Are you looking for userspace instrumentation? Please see [this page](/docs/event-sources/drivers/#userspace-instrumentation).
```
Thanks,
tonghuaroot
=> Update userspace instrumentation Link.

content/en/docs/rules/_index.md
Signed-off-by: tonghuaroot tonghuaroot@gmail.com
> /kind bug
Fixed a typo in the document. From ```filees``` to ```files```.
Thanks,
tonghuaroot
=> Fixed a typo in the document.From filees to files.

config.toml
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
This PR adds a link to community call records:
Fixes #
=> add links to community calls records

config.toml
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Update Falco release information to `0.31.1` in the configuration file.
Fixes #
=> update(config.toml): update for version 0.31.1

content/en/blog/falco-0-31-1.md
> /kind bug
> /kind design
/kind content
/area blog
> /area videos
Falco 0.31.1 has been released this week. This PR adds a blog post to highlight the recent changes.
Fixes #
=> new(blog): add entry for falco 0.31.1

content/en/docs/rules/supported-fields.md
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
We recently released Falco 0.31.1, this PR updates the fields documentation with the latest additions.
Fixes #
=> update(fields): add fields for 0.31.1

content/en/blog/falco-0-31-1.md
/kind bug
> /kind design
/area blog
> /area videos
This is the 0.31.1 release, not 0.30.0 🤦‍♂️ 
Thanks @FedeDP for noticing.
Fixes #
=> fix(blog): fix typo stable 0.30.0 -> 0.31.1

content/en/docs/event-sources/cloudtrail.md
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Fixes #
=> fix(docs): repo url for Terraform AWS CloudTrail module

config/_default/config.toml
Signed-off-by: Federico Di Pierro <nierro92@gmail.com>
> /kind bug
/kind cleanup
> /kind design
> /area blog
> /area videos
Fixes #
=> update(config): archive 0.31.

config/_default/config.toml
Signed-off-by: Federico Di Pierro <nierro92@gmail.com>
> /kind bug
/kind cleanup
> /kind design
/area blog
> /area videos
Fixes #
=> update(config): updated website config for 0.32.0.

content/en/blog/falco-0-32-0.md
Signed-off-by: Federico Di Pierro <nierro92@gmail.com>
> /kind bug
> /kind design
/kind content
/area blog
> /area videos
Fixes #
=> new(content): added Falco 0.32 blog post

release.md
```
```
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Fixes #
=> docs: change order of instruction steps for website snapshot

content/en/docs/rules/supported-fields.md
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
This PR updates the fields for version 0.32.0. In addition, the one-liner to generate the list with Falco has been updated. This adds an extra newline before each table which shouldn't change the rendering, the preview will confirm that.
Fixes #
=> update(docs): update supported fields for 0.32.0

content/zh/blog/contribution-drivers-kmod-ebpf-libraries.md
Add contribution-drivers-kmod-ebpf-libraries.md  Chinese document, easy for readers to read.
Signed-off-by: qinzhiben <qinzhiben@uniontech.com>
=> add contribution-drivers-kmod-ebpf-libraries.md

content/zh/blog/cloud-native-security-hub.md
add cloud-native-security-hub.md file, Bring better reading experience to readers
Signed-off-by: wanhui <wanhui@uniontech.com>
=> Add cloud-native-security-hub.md

content/en/docs/getting-started/installation.md
/kind content
This PR includes a sysctl command in the documentation to check that the host has `net.core.bpf_jit_enable` set to 1.
**Which issue(s) this PR fixes**: 
N/A
=> Sepcifying how to check bpf_jit_enable is set to 1

content/zh/blog/falco-0-21-0.md
falco-0-21-0.md file translate Chinese
=> falco-0-21-0.md file translate Chinese

content/zh/falco-0-22-x.md
falco-0-22-x.md file translate Chinese
=> falco-0-22-x.md file translate Chinese

content/zh/falco-0-23-0.md
falco-0-23-0.md file translate Chinese
=> falco-0-23-0.md file translate Chinese

content/en/docs/plugins/go-sdk-walkthrough.md
=> docs(content/docs/plugins): document Go SDK source instance prebuilts

content/zh/blog/falco-0-25-0.md
falco-0-25-0.md file translate Chinese
=> falco-0-25-0.md file translate Chinese

content/zh/blog/detect-cve-2020-8557.md
Add detect-cve-2020-8557.md Chinese file
=> Add detect-cve-2020-8557.md Chinese file

content/zh/extend-falco-outputs-with-falcosidekick.md
extend-falco-outputs-with-falcosidekick.md file translate Chinese
=> extend-falco-outputs-with-falcosidekick.md file translate Chinese

layouts/blog/list.html
Signed-off-by: Issif <issif+github@gadz.org>
> /kind bug
/kind design
/area blog
> /area videos
This PR adds the Author name aside each posts in the list of blog posts.
Before:
After:
Fixes #
=> display the Author Name in the list of Blog posts

content/zh/extend-falco-inputs-with-a-plugin-the-basics.md
extend-falco-inputs-with-a-plugin-the-basics.md file translate Chinese
Signed-off-by: tianying [tianying@uniontech.com](mailto:tianying@uniontech.com)
=> extend-falco-inputs-with-a-plugin-the-basics.md file translate Chinese

content/zh/blog/falco-0-24-0.md
falco-0-24-0.md file translation Chinese
=> falco-0-24-0.md file translation Chinese

content/zh/blog/falco-0-26-2.md
falco-0-26-2.md file translation Chinese
Signed-off-by: tianying [tianying@uniontech.com](mailto:tianying@uniontech.com)
=> falco-0-26-2.md file translation Chinese

layouts/_default/content.html, layouts/docs/list.html, layouts/partials/page-meta-lastmod-short.html
Signed-off-by: Issif <issif+github@gadz.org>
> /kind bug
> /kind design
> /area blog
> /area videos
This PR adds the Last Modification date under the title of each page, it avoids to scroll til the bottom to check if the page may be obsolete. It's a short version, the link to the last commit is still only displayed in the line at bottom.
Fixes #
=> add last modification date under title in its short version

.vscode/settings.json, content/en/blog/extend-falco-inputs-with-a-plugin-the-basics.md
Signed-off-by: Issif <issif+github@gadz.org>
> /kind bug
> /kind design
/kind content
/area blog
> /area videos
Update the blog post [Extend Falco inputs by creating a Plugin: the basics](https://falco.org/blog/extend-falco-inputs-with-a-plugin-the-basics/) to follow last features of the Plugin GO SDK
Fixes #
=> update blog post Extend Falco inputs by creating a Plugin: the basics

config/_default/config.toml
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Usual update to the config file for 0.32.1
Fixes #
=> update(docs): update config.toml for v0.32.1

content/en/docs/getting-started/deployment.md
Signed-off-by: TERAOKA Keisuke [todavingt@gmail.com](mailto:todavingt@gmail.com)
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
- I modified the example URL at DaemonSet on this page.
- https://falco.org/docs/getting-started/deployment/
- The previous URL `https://github.com/falcosecurity/evolution/tree/master/deploy/kubernetes/falco/templates` is 404 because I think kubernetes deployments templates were moved to [this repo](https://github.com/falcosecurity/deploy-kubernetes). …
=> update(docs): update the example url at DaemonSet on Kubernetes Deployment Document

content/zh/blog/falco-0-27-0.md
falco-0-27-0.md file translation Chinese
=> falco-0-27-0.md file translation Chinese

content/zh/blog/falco-0-28-1.md
falco-0-28-1.md file translation Chinese
=> falco-0-28-1.md file translation Chinese

OWNERS
> /kind bug
> /kind design
/kind content
/area blog
> /area videos
Fixes #
=> Adding vjjmiras as a reviewer

content/en/blog/choosing-a-driver.md
> /kind bug
> /kind design
/kind content
/area blog
> /area videos
Fixes #616
=> Fix/Update URLs in the blog post

content/en/blog/falco-0-32-2.md
/kind content
/area blog
Add a blog entry to announce the new Falco `0.32.2` release.
=> new(blog): Falco `0.32.2` release post

config/_default/config.toml
/kind content
Usual update to the config file for 0.32.2
=> update(config.toml): bump falco version to `0.32.2`

content/en/docs/_index.md, content/en/docs/alerts/_index.md, content/en/docs/changelog/_index.md, content/en/docs/configuration/_index.md, content/en/docs/contribute/_index.md, content/en/docs/event-sources/_index.md, content/en/docs/examples/_index.md, content/en/docs/getting-started/_index.md, content/en/docs/grpc/_index.md, content/en/docs/plugins/_index.md, content/en/docs/rules/_index.md
> /kind bug
/kind cleanup
> /kind design
> /area blog
> /area videos
Fixes #670
=> Increase separation between menu elements

content/en/blog/updating-falco-governance.md
Co-authored-by: Jason Dellaluce <jasondellaluce@gmail.com>
> /kind bug
> /kind design
/kind content
/area blog
> /area videos
Fixes #
=> docs(content/en/blog): Updating Falco’s governance

content/en/blog/falco-driverkit-debian-docker.md
> /kind bug
> /kind design
/kind content
/area blog
> /area videos
Fixes #
=> Blog Driverkit for Debian/Docker

content/en/docs/event-sources/cloudtrail.md
Signed-off-by: Trevor Sullivan <trevor@trevorsullivan.net>
Signed-off-by: Trevor Sullivan <trevor@trevorsullivan.net>
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> Update link to CloudTrail plugin rules

Makefile
/kind bug
> /kind design
/area blog
> /area videos
Fixes #
=> Addig GitHub rate limit to production build

content/en/blog/intro-gvisor-falco/index.md
> /kind bug
> /kind design
/kind content
/area blog
> /area videos
Fixes #
=> Added images to metadata for social

content/en/blog/falco-m1.md
/kind content
/area blog
It adds a new article to the Falco blog on how to install Falco on Apple Silicon via Lima
None
Fixes #
None
I was wondering if including how to install Falco on K8s on M1, but I don't know if the article length would be too much. Thoughts?
=> new(blog): Small how-to for Falco on M1 via Lima

content/en/docs/getting-started/third-party/production.md
> /kind bug
> /kind design
> /area blog
> /area videos
Update some outdated helm commands.
Fixes #
=> update(docs): use the correct helm options based on v2.0.0 of the faco chart

assets/scss/_changelog.scss, assets/scss/_styles_project.scss, config/_default/config.toml, content/en/docs/changelog/_index.md, content/en/docs/grpc/outputs.md, content/en/docs/grpc/version.md, layouts/shortcodes/changelog.html, layouts/shortcodes/github_alert.html, layouts/shortcodes/githubcode.html
/kind bug
> /kind design
> /area blog
> /area videos
/hold 
Fixes #
=> Added HUGO_GITHUB_TOKEN option to GitHub API calls

content/en/docs/getting-started/third-party/learning.md
> /kind bug
> /kind design
> /area blog
>/area documentation
> /area videos
Update `minikube` docs to reflect the changes introduced in Falco 0.33.0 release.
Fixes https://github.com/falcosecurity/falco/issues/1941
=> update(learning.md): sync with docs changes of Falco 0.33.0 about minikube

content/en/docs/getting-started/running/_index.md
/kind cleanup
Bumps Running page with latest informations for Falco 0.33.
Fixes #
=> chore(content): updated running page with newest informations.

.gitignore, content/en/docs/event-sources/drivers.md
/kind cleanup
/kind content
This PR tries to refresh the content of the `Falco Drivers` page with up-to-date info 
=> update(sources/drivers): refresh `Falco Drivers` page with updated info

content/en/docs/plugins/plugin-api-reference.md
/kind cleanup
This syncs the plugin API reference with the new definitions coming from Falco 0.33.0.
/hold until Falco 0.33.0 gets released
=> update(content/en/docs): sync plugin api reference with Falco v0.33

config/_default/config.toml
/kind content
Update website version to v0.33
/hold until Falco 0.33 gets released
=> update(config.toml): update website to v0.33

content/en/blog/falco-0-33-0.md
/kind content
/area blog
/hold until Falco 0.33 gets released
=> new(content/en/blog): add post for Falco 0.33

content/en/docs/getting-started/third-party/learning.md
```
```
> /kind bug
> /kind design
> /area blog
> /area videos
Update the minikube docs to enable the k8s audit logging in minikube. Add detailed steps on how to deploy Falco using `k8saudit` and `syscall` sources.
Fixes #
=> update(learning/minikube): docs to deploy falco with syscall and k8saudit on minikube

content/en/docs/getting-started/third-party/learning.md
/kind content
Add command in the `minikube` documentation
=> update(learning): add a command in minikube doc

content/en/docs/getting-started/third-party/learning.md
> /kind bug
> /kind design
> /area blog
> /area videos
Remove some extra steps when creating the configuration files in the minikube setup.
Fixes #
=> update(docs/minikube): avoid extra steps during the creation of config files

.github/dependabot.yml
> /kind bug
/kind cleanup
> /kind design
> /area blog
> /area videos
Fixes #
=> new(.github): add dependabot

content/en/blog/falco-applies-for-graduation.md
/kind content
/area blog
Fixes #
=> docs(blog): Falco applies for graduation

content/en/blog/falco-at-kubecon-na-2022/index.md
Signed-off-by: jsalinas29 <salinas.jacque@gmail.com>
> /kind bug
> /kind design
/kind content
/area blog
> /area videos
Fixes #
=> add video to falco kubecon post

netlify.toml
> /kind bug
/kind design
> /area blog
> /area videos
Fixes #
=> update(netlify build): NPM version to 9.1.1

config/_default/versions/params.yaml
/kind cleanup
When 0.33.1 is released, update the configuration files
Fixes #
=> update(config): update version number for 0.33.1

content/en/blog/falco-0-33-1.md
/kind content
/area blog
Add an entry for Falco 0.33.1 release ( when the release completes :D )
Fixes #
=> new(blog): add entry for Falco 0.33.1

content/en/docs/tutorials/index.md
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Fixes #
=> add tutorials section

layouts/partials/head.html
> /kind bug
> /kind design
/kind content
/area blog
> /area videos
Fixes #
=> add(header): fields canonicalURL/canonical_url to Frontmatter

content/en/docs/reference/changelog/index.md
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Fixes #
/hold until PR #736 is merged
=> move changelog section under reference

content/en/blog/falco-on-aws.md
> /kind bug
> /kind design
/kind content
/area blog
> /area videos
Fixes #
=> new(blog): Falco on AWS Cloud

assets/scss/_pageinfo.scss, assets/scss/_styles_project.scss, assets/scss/_version_banner.scss, layouts/partials/version-banner.html
> /kind bug
/kind design
> /area blog
> /area videos
Fixes #
=> update(css): pageinfo size to 70%

content/en/docs/alerts/_index.md
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Fixes #
=> move Falco alerts section up

layouts/blog/list.html
> /kind bug
/kind design
/area blog
> /area videos
Fixes #
=> changed featured image proportion from 2x to 1.9x

content/en/docs/contribute/_index.md, content/en/docs/contribute/contributor-of-the-month.md, content/en/docs/getting-started/source.md, content/en/docs/grpc/_index.md, content/en/docs/reference/_index.md, content/en/docs/reference/changelog/index.md, content/en/docs/reference/rules/_index.md, content/en/docs/reference/rules/default-macros/index.md, content/en/docs/reference/rules/macros-override/index.md, content/en/docs/reference/rules/rule-fields/index.md, content/en/docs/reference/rules/supported-events/index.md, content/en/docs/rules/_index.md, content/en/docs/supported-doc-versions.md, content/en/docs/tutorials/_index.md
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Fixes #
=> update(docs): add descriptions where missing in frontmatter

netlify.toml
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> bump hugo to 108.0 and npm to 9.2.0

content/en/docs/reference/rules/supported-fields/index.md
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> update(docs): more detail about container runtime populated k8s fields

content/en/docs/getting-started/running/index.md
/kind content
We just deployed Falco and one of the things we quickly found was the need to validate rules locally but couldn't find instructions in the documentation. So I think this might be useful for others. 
Fixes #
=> Add instructions how to validate Falco rules locally with Docker

content/en/blog/falco-packages-gpg-key-rotated.md
/kind bug
/area blog
This PR fixes some broken links
=> docs(blog): fix some broken links

content/en/blog/falco-packages-gpg-key-rotated.md
/kind content
/area blog
This PR adds an example for the gpg key rotation post. This should make updating easier for users that are receiving an unexpected error when trying to read packages from the Falco repo.
Fixes #
=> update(blog): add example with error for deb-gpg

content/OWNERS, layouts/OWNERS
> /kind bug
> /kind design
/kind content
/area blog
> /area videos
Fixes #
I'm proposing myself as an approver to the directories relevant for the content and interface of Falco website.
=> Vote: add vjjmiras as an approver to content/ and layouts/

config/_default/versions/params.yaml
/kind content
Update the website for Falco 0.34.0
Fixes #
=> new(website): add v0.34.0 to params.yaml

content/en/docs/event-sources/drivers.md, content/en/docs/getting-started/running/index.md
/kind content
This PR updates the modern BPF probe for Falco 0.34.
This PR depends on https://github.com/falcosecurity/falco-website/pull/799
=> update(content): support modern bpf probe as a new driver

content/en/docs/event-sources/drivers.md
/kind content
This PR fixes some broken links in the modern bpf section
=> update(docs): fix some broken links in the modern bpf probe

content/en/docs/getting-started/third-party/learning.md
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Update the `minikube` tutorial to reflect the latest changes introduced in chart `v3.0.0`.
Fixes #
=> update(docs): use latest chart values in  minikube tutorial

content/en/blog/rules-helm-chart-3-0-0.md
/kind content
/area blog
Add a simple guide in our blog for the most common use cases of the new Helm chart
Fixes #
=> new(blog): rules and helm chart 3.0.0

content/en/blog/rules-helm-chart-3-0-0.md
/kind bug
/area blog
as per title
Fixes #
=> update(blog): remove double title on helm 3.0.0 article

config/_default/config.toml, content/en/docs/plugins/registered-plugins.md, layouts/shortcodes/plugins.html
Signed-off-by: Thomas Labarussias <issif+github@gadz.org>
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
This PR introduces the table of all registered plugins. Everything is collected automatically from the plugins repo:
Fixes #
=> list registered plugins in plugins section

content/en/blog/rules-helm-chart-3-0-0.md
/kind bug
/area blog
yes.
Fixes #
=> fix(blog): fix typo in latest rules entry

content/en/docs/event-sources/drivers.md
Signed-off-by: Pablo Musa <pmusa@users.noreply.github.com>
=> Clarify experimental reason #1

content/en/blog/falco-0-34-1.md
> /kind bug
> /kind design
/kind content
/area blog
> /area videos
Add a blog entry to announce the new Falco 0.34.1 release.
Fixes #
=> new(blog): falco 0.34.1 release post

config/_default/versions/params.yaml
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Update the website for Falco 0.34.1
Fixes #
=> update(config): update version number for 0.34.1

content/en/docs/rules/default-custom.md
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Add a link to the repo of the rules
Fixes #
=> add a link to the gh repo for the rules

assets/scss/_code.scss, assets/scss/_styles_project.scss, assets/scss/_tables.scss, assets/scss/_variables_project.scss
> /kind bug
/kind design
> /area blog
> /area videos
This PR has tables and code blocks design updates for documentation section
#818
Fixes #
=> Feat: documentation section tables and code blocks redesign

layouts/shortcodes/card.html
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Updates card shortcode, so it could take param with defferent content types
Fixes #
=> feat: update card shortcode

config/_default/config.toml
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Adds a dropdown community menu with description
Fixes #
=> feat: add community menu

assets/scss/_nav.scss, assets/scss/_tabs.scss, assets/scss/_utilities.scss, assets/scss/_variables_project.scss, layouts/partials/page-meta-links.html, layouts/shortcodes/tabs.html
> /kind bug
/kind cleanup
> /kind design
> /area blog
> /area videos
Sidebar navigation design updated
Tabbed content design updated
Fixes #
=> Feat: document section sidebar navigation revamp

content/en/about/ecosystem.md
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Added end-users to about/ecosystems page
#817
Fixes #
=> fix: added endusers to ecosystems page

content/en/blog/falco-0-34-0/index.md, content/en/blog/falco-detect-cryptomining/index.md, content/en/blog/falco-modern-bpf/index.md, content/en/blog/falcosidekick-2-27-0-ui-2-1-0/index.md, content/en/blog/intro-gvisor-falco/index.md, content/en/blog/recap-2022/index.md
> /kind bug
/kind cleanup
> /kind design
/area blog
> /area videos
Fixes #
=> fix: remove duplicated featured image inclusion

content/en/blog/falco-security-audit-2023.md
/kind content
/area blog
Add information about the latest Falco security audit
Fixes #
=> new(blog): add article about the 2023 security audit

assets/js/announcement-bar.js, assets/js/feedback.js, assets/scss/_announcement.scss, assets/scss/_styles_project.scss, data/en/announcements/announcement.yaml, layouts/_default/baseof.html, layouts/partials/announcement-bar.html, layouts/partials/hooks/head-end.html
> /kind bug
> /kind design
> /area blog
> /area videos
Announcement bar UI and business logic
Fixes #
#825
=> feat: announcement bar

content/en/about/falco.md, content/en/about/use-cases.md, content/en/about/why-falco.md, layouts/partials/head.html
> /kind bug
> /kind design
> /area blog
> /area videos
Implements optional logic in head.html that enables to add keywords in frontmatter of md files
Fixes #
=> feat: add keywords logic to head.html

assets/scss/_nav.scss, layouts/partials/navbar.html
> /kind bug
/kind design
> /area blog
> /area videos
This PR fixes minor issues of navbar
#825 
Fixes #
=> fix: navbar minor issues

assets/scss/_card.scss, content/en/about/ecosystem.md, content/en/about/falco.md, content/en/about/faq.md, content/en/about/use-cases.md, content/en/about/why-falco.md, content/en/community/contributors.md, layouts/partials/training-content.html
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Adds styles to faq_card, remove redundant html with classes. Updates styles on tarining page. Adds links to contributors page.
Fixes #
=> feat: change styles of faq-card, add styles to training elements

ADD_CONTRIBUTOR.md, ADD_NOMINATION.md, assets/scss/_tables.scss, assets/scss/_variables_project.scss, content/en/community/contributors.md, data/contributors.yaml, data/nominations.yaml, layouts/community/contributors.html, layouts/partials/contributors.html, layouts/partials/nominations.html
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Extract contributors data to separate file. Add partial/contributors, layout/contributors, add related links
Fixes #
=> Feat: update contributors

assets/js/announcement-bar.js, assets/js/subscribe-form.js, assets/js/videos.js, assets/scss/_card.scss, assets/scss/_landing.scss, data/en/announcements/kubecon-eu.yaml, layouts/partials/announcement-bar.html, layouts/partials/landing/features.html
> /kind bug
/kind design
/kind content
> /area blog
> /area videos
Fixes landing page minor issues
#825 
Fixes #
=> fix: landing page minor issues

layouts/shortcodes/content_arrow.html
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Fix of arrow-content, add text-body style
Fixes #
=> fix: update content-arrow shortcode

assets/scss/_nav.scss
> /kind bug
> /kind design
> /area blog
> /area videos
This PR fixes HTML spaces issue in production
Fixes #
=> fix: navbar design

config/_default/config.toml, content/en/docs/alerts/formatting.md, layouts/_default/content.html, layouts/docs/baseof.html, layouts/docs/list.html
> /kind bug
/kind design
/kind content
> /area blog
> /area videos
Docs section minor issues 
Fixes #
=> fix: docs minor issues

data/training/offerings/detect-cryptomining.yaml, layouts/partials/training-content.html
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Updates content of training page.
Fixes #
=> fix: update training

i18n/en/en.yaml
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Change link contribute to blog.
Fixes #
=> fix: update contribute to blog link

data/en/events.yaml
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes event date
Fixes #
=> fix: event date

layouts/partials/footer.html
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Delete text from footer
Fixes #
=> fix: delete text from footer

assets/scss/_utilities.scss
> /kind bug
> /kind design
> /area blog
> /area videos
Fix styles that overlap content above and beyond header, so button elements become unclickable and unbale to interact with.
Fixes #
=> fix: rewrite headers style that overlap content

config/_default/config.toml, layouts/partials/navbar.html
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Change name of english language from `Eng` to `English`, move arrow from left to right
Fixes #
=> fix: change english language name and arrow location

ADD_CONTRIBUTOR.md, data/contributors.yaml, layouts/partials/contributors.html
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Adds description field to first two contributors of the month. Update instruction md file.
Fixes #
=> feat: add description field to contributors

assets/js/copy-link.js, assets/scss/_styles_project.scss, assets/scss/_toasts.scss, data/en/announcements/kubecon-eu.yaml, layouts/blog/baseof.html, layouts/blog/content.html, layouts/partials/blog/card.html, layouts/partials/hooks/head-end.html, layouts/partials/toast.html
/kind bug
/kind design
/area blog
> /area videos
This PR fixes blog "Copy link" buttons. Added toast message
#824 
Fixes #
=> Fix: blog links and covers

content/en/blog/falco-aws-security-lake/index.md
> /kind bug
> /kind design
/kind content
/area blog
> /area videos
Update of the IAM section for AWS Security Lake post
Fixes #
=> update section about IAM

content/en/docs/getting-started/third-party/learning.md
/kind bug
This PR fixes the rendering of some yaml blocks
=> fix: add some spaces after pageinfo

data/contributors.yaml
adding Federico since he won march 2023
pic + info and winning description 
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
adding content to contributor page - march 2023 winner
Fixes #
Signed-off-by: jsalinas29 <salinas.jacque@gmail.com>
=> adding march 2023 contributor of the month

layouts/blog/content.html, layouts/partials/blog/card.html
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes copy blog link with quotes issue
Fixes #
=> fix: copy blog link quotes

assets/js/events.js, assets/scss/_community.scss, data/en/announcements/kubecon-eu.yaml, data/en/events.yaml, layouts/community/list.html, layouts/partials/community/events.html, layouts/partials/community/webcasts.html
/kind bug
> /kind design
/kind content
> /area blog
> /area videos
Events section minor issues
Fixes #
=> fix: events minor issues

assets/scss/_consent.scss, assets/scss/_styles_project.scss, layouts/partials/cookie_consent.html, layouts/partials/head.html
> /kind bug
> /kind design
> /area blog
> /area videos
Cookie consent banner
Fixes #
=> feat: cookie consent banner

assets/scss/_utilities.scss
/kind bug
> /kind design
> /area blog
> /area videos
Fixes the incorrect scrol lto the header elements.
Fixes #
=> fix: add property to css to fix incorrect scroll position

assets/scss/_tabs.scss, content/en/about/ecosystem.md, layouts/shortcodes/blocks/tabs.html, layouts/shortcodes/footer_nav.html
> /kind bug
> /kind design
> /area blog
> /area videos
About/Falco ecosystems responsive view
Fixes #
=> feat: about ecosystem responsive layout

content/en/about/falco.md, content/en/about/use-cases.md, layouts/partials/head.html
> /kind bug
> /kind design
> /area blog
> /area videos
Adds keywords to some pages. Update parsing keywords logic, so phrases consisting of 2 words don't get joined into one.
Fixes #
=> feat: add keywords

layouts/partials/navbar.html
> /kind bug
/kind design
> /area blog
> /area videos
Centers the navbar menu.
Fixes #
=> fix: center the navbar menu items

content/en/about/use-cases.md
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Change width of content.
Fixes #
=> feat: change width of the content

layouts/partials/announcement-bar.html, layouts/partials/navbar.html, layouts/shortcodes/content_arrow.html
> /kind bug
/kind cleanup
> /kind design
> /area blog
> /area videos
Update accessibility of why-falco page.
Fixes #
=> fix: accessibility of why-falco

assets/js/community-videos.js, assets/js/events.js, content/en/about/ecosystem.md, layouts/partials/footer.html
> /kind bug
> /kind design
> /area blog
> /area videos
Update accessibility of about and community sections.
Fixes #
=> fix: update about, community sections accessibility

ADD_EVENT.md, assets/js/events.js, assets/js/slider.js, assets/scss/_community.scss, data/en/events.yaml, layouts/partials/community/events.html, package-lock.json, package.json
/kind bug
> /kind design
> /area blog
> /area videos
Adds date formatting to community/events
Fixes #
=> Fix: community events

content/en/community/events.md
> /kind bug
/kind cleanup
> /kind design
> /area blog
> /area videos
Remove unused content fron events.md
Fixes #
=> fix: remove content from events.md

assets/js/community-videos.js, assets/js/videos.js, functions/youtube-bypass.js
Signed-off-by: veralex <alexey.verevkin@akvelon.com>
feat: added get videos to functions
/kind bug
> /kind design
> /area blog
> /area videos
Fixes youtube videos date issue
Fixes #
=> feat: added get videos to functions

assets/js/events.js, layouts/partials/community/events.html, layouts/partials/landing/events.html
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes landing page events script
Fixes #
=> fix: landing page events script restored

assets/js/copy-link.js, assets/scss/_card.scss, layouts/_default/baseof.html, layouts/partials/card_faq.html
> /kind bug
> /kind design
> /area blog
> /area videos
Added FAQ card copy link button
Fixes #918
=> fix: added faq card copy link button

layouts/community/falco-brand.html
/kind bug
> /kind design
> /area blog
> /area videos
Text `Cloud Native Runtime Security` was changed from h4 tag to p tag
Fixes #
=> fix: update font size

content/en/blog/falco-kind-prometheus-grafana.md
> /kind bug
/kind cleanup
> /kind design
> /area blog
> /area videos
Fixes #
Issue #834 
=> fix: correct link to gRPC certificates config

data/nominations.yaml, layouts/partials/nominations.html
/kind bug
> /kind design
> /area blog
> /area videos
Fixes nominations behaviour: once the month's over, nomination is no more active
Fixes #
=> fix: nominations logic

content/en/blog/drivers-add-new-distro.md
/kind content
/area blog
Adding support for a new distro in our artifacts shipping flow is pretty hard; since the introduction of kernel-crawler it is even "harder" because it involves a new repo.
Finally explain the procedure ;) 
Fixes #
=> new(blog): added a blog post about adding support for a new distro for our prebuilt drivers

content/en/docs/getting-started/installation.md
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Fixes #
This corrections extend the ones sent by @sgaist in PR #816 
=> instructions formatted for a more logical sequence

assets/js/videos.js
/kind bug
> /kind design
> /area blog
> /area videos
Fixes #965 
=> fix: youtube videos urls for landing page

data/en/events.yaml
> /kind bug
> /kind design
/kind content
> /area blog
/area videos
Fixes #
=> new: Upcoming Falco workshop with AICamp

layouts/index.en.html
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Fixes #
=> fix: url for community events

data/en/events.yaml
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Fixes #
=> new: add upcoming Falco workshops events

assets/scss/_community.scss, i18n/en/community/en.yaml, layouts/community/events.html
> /kind bug
/kind design
> /area blog
> /area videos
Fixes #
=> fix(events): update CSS format of event card

config/_default/config.toml
Contributes to:
- #972
/kind cleanup
/cc @LucaGuerra @leogr
=> Drop UA ID

content/en/docs/getting-started/running/index.md
/kind content
This PR adds a comment because the actual docker command doesn't work on kernel versions < 4.17 when we use the bpf probe
https://github.com/falcosecurity/falco/issues/2603
=> fix(content): update documentation of BPF with docker

data/en/events.yaml
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Fixes #
=> add(events): Falco workshop on Bellevue

content/en/docs/getting-started/try-falco/try-falco-on-kubernetes/index.md, content/en/docs/getting-started/try-falco/try-falco-on-ubuntu/index.md, content/en/docs/getting-started/try-falco/try-falcosidekick-on-kubernetes/index.md, content/en/docs/getting-started/try-falco/try-falcosidekick-on-ubuntu/index.md
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Fixes #
=> Remove command line prompts and update installing instructions

content/en/blog/gitops-your-falco-rules/index.md
…etes
> /kind bug
> /kind design
/kind content
/area blog
> /area videos
Fixes #
=> fix(blog): fixing some errors on the instructions to deploy on Kubernetes

content/en/blog/falco-0-35-0/index.md
/kind content
/area blog
New 0.35.0 release blog post :) 
Fixes #
=> new(content): Falco 0.35.0 blog post

content/en/docs/getting-started/installation.md
/kind content
Add info about cosign support in falco 0.35.0 and newer
Fixes #
=> new(docs): add container signature documentation

content/en/blog/falco-0-35-0/index.md
/kind content
> /area blog
Added the youtube video to the launch blog for ease of access / increased information
N/A
=> Added YouTube Video

content/en/docs/event-sources/kernel.md, content/en/docs/getting-started/running/index.md
/kind content
This PR updates the documentation of the modern bpf probe -> no more experimental
This is for Falco 0.35
=> update(docs): update modern bpf documentation

content/en/blog/falco-0-35-0/index.md
> /kind bug
> /kind design
/kind content
/area blog
> /area videos
Fixes #
**Special notes for your reviewer**: searching on Google for "falco releases" the third result (the first one after the "github") link to https://falco.org/tags/release/ where the announcement related to Falco 0.35 was missing.
=> Update: add missing tags in the falco 0.35 release announcement

assets/js/feedback.js, config/_default/config.toml
- Closes #974
/cc @aijamalnk
/kind bug
=> Send page feedback using gtag

content/en/docs/reference/rules/supported-fields/index.md
/kind content
As per title, updating the docs with new fields.
Fixes #
=> update(content): update fields for 0.35.0

data/en/features.yaml, data/en/usecases.yaml, i18n/en/en.yaml
Updating Falco's landing page with feedback from CNCF's TOC. Rephrasing a few things.
/kind cleanup
TOC gave specific feedback about some of the wording on the site. I am editing to match here.
Related to https://github.com/falcosecurity/falco-website/issues/1003
=> Update en.yaml based on TOC feedback.

ADD_EVENT.md
/kind bug
> /kind design
> /area blog
> /area videos
=> fix: switch case study for events

content/en/about/_index.md, content/en/about/why-falco.md
Removing "respond" from About section in "Why Falco" and What is Falco" pages.
/kind cleanup
Clarifies what falco does
Related to https://github.com/falcosecurity/falco-website/issues/1003
=> Update _index.md based on TOC feedback

config/_default/versions/params.yaml
> /kind bug
> /kind design
> /area blog
> /area videos
As per PR title
Fixes #
=> update(params.yaml): bump website to falco v0.35.1

content/en/blog/falco-0-35-1.md
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> docs: add blog post about 0.35.1 release

content/en/blog/falco-0-35-1.md
/kind bug
> /kind design
/area blog
> /area videos
fix in a typo in the falco 0.35.1 blog post
Fixes #
=> fix typo in falco 0.35.1 blog post

assets/scss/_glossary.scss, assets/scss/_styles_project.scss, content/en/docs/reference/glossary/index.md, data/canonical-tags/architecture.yaml, data/canonical-tags/community.yaml, data/canonical-tags/extension.yaml, data/canonical-tags/fundamental.yaml, data/canonical-tags/tool.yaml, i18n/en/glossary/en.yaml, layouts/docs/glossary.html, layouts/partials/docs/glossary-terms.html, layouts/shortcodes/glossary_definition.html, layouts/shortcodes/glossary_tooltip.html, static/js/glossary.js
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Fixes #
=> feature: add glossary layout

content/en/blog/falco-pci-dss/index.md
> /kind bug
> /kind design
/kind content
/area blog
> /area videos
Fixes #
=> update(blog): fixing wrong rule

content/en/docs/grpc/client-go.md, content/ja/docs/grpc/client-go.md, content/ml/docs/grpc/client-go.md
> /kind bug
/kind cleanup
> /kind design
> /area blog
> /area videos
Fixes #
=> fix(documentation): change cert path for client-go

config/_default/config.toml, config/_default/languages/languages.yaml
> /kind bug
/kind cleanup
> /kind design
> /area blog
> /area videos
Fixes #
=> fix(i18n): deprecation of custom params for languages

ADD_BLOG.md
> /kind bug
> /kind design
/kind content
/area blog
> /area videos
Fixes #
=> update(blog): extend instructions to add a blog entry

data/en/events.yaml
> /kind bug
> /kind design
/kind event
> /area blog
> /area videos
Fixes #
=> update(events): add CNCF Livestream July 2023

content/en/docs/_index.md
/kind content
In order for people to better find the complete list of repositories that has been recently revamped we can link the evolution repo directly from the about page, which serves as an entry point for adopters that wish to learn more about the components of the Falco ecosystem.
Fixes #1004 
=> update(docs): improve linking between Falco and ecosystem in the about page

content/en/docs/reference/glossary/abnormal-behavior.md, content/en/docs/reference/glossary/alerts.md, content/en/docs/reference/glossary/conditions.md, content/en/docs/reference/glossary/eBPF.md, content/en/docs/reference/glossary/exceptions.md, content/en/docs/reference/glossary/falco.md, content/en/docs/reference/glossary/falcoctl.md, content/en/docs/reference/glossary/falcosidekick-ui.md, content/en/docs/reference/glossary/falcosidekick.md, content/en/docs/reference/glossary/fields.md, content/en/docs/reference/glossary/grpc.md, content/en/docs/reference/glossary/kernel-space.md, content/en/docs/reference/glossary/kernel.md, content/en/docs/reference/glossary/libscap.md, content/en/docs/reference/glossary/libsinsp.md, content/en/docs/reference/glossary/lists.md, content/en/docs/reference/glossary/macros.md, content/en/docs/reference/glossary/plugins.md, content/en/docs/reference/glossary/response-engine.md, content/en/docs/reference/glossary/rules-file.md, content/en/docs/reference/glossary/rules.md, content/en/docs/reference/glossary/runtime-security.md, content/en/docs/reference/glossary/syscalls.md, content/en/docs/reference/glossary/tags.md, content/en/docs/reference/glossary/user-space.md, data/canonical-tags/event-source.yaml, data/canonical-tags/integration.yaml, data/canonical-tags/security-concept.yaml
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Fixes #
=> add first glossary terms

content/en/blog/adaptive-syscalls-selection/index.md
/kind bug
/kind content
/area blog
Move the lab part outside of the pageinfo. Fix broken image link.
=> Fix Adaptive Syscalls Blog Lab snippet.

content/en/blog/nist-controls/index.md
/kind cleanup
/area blog
r: @LucaGuerra
=> Adding links to nist-controls blog post

layouts/docs/glossary.html
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> feat(glossary): remove show more (plus sign) option when empty

data/en/usecases.yaml, layouts/partials/landing/use-cases.html
/kind cleanup
To address TOC feedback on Falco use cases
Fixes #1035
Do not merge yet
=> Update usecases.yaml on the landing page

data/en/features.yaml
/kind cleanup
For consistency of the new messaging 
Doesn't fix but related to #1003
=> Update features descriptions on the landing page

content/en/docs/event-sources/kernel.md
/kind content
This PR adds the necessary `bpftool` commands to check modern bpf requirements on your system
=> update(docs): add `bpftool` commands to check modern bpf requirements

content/zh-cn/blog/falco-0-31-0.md
Add falco-0-31-0.md Chinese file
=> Add falco-0-31-0.md Chinese file

content/en/docs/rules/controlling-rules.md
This PR provides an update on the example of how to disable rules using macros, that reflects the latest version of Falco.
Fixes #1067 
=> Updating rule disable through macro section

content/en/blog/falco-mitre-attack/index.md
Signed-off-by:   ashutoshmore658 (ashutoshmore658@gmail.com) (CloudDefense.AI)
/kind content
/area blog
This PR adds a link in the blog , which was previously missing.
=> adds the missing link

data/en/events.yaml
> /kind bug
> /kind design
/kind event
> /area blog
> /area videos
Fixes #
=> fix(events): time of Falco workshop

content/en/docs/getting-started/try-falco/try-falco-on-kubernetes/index.md, content/en/docs/getting-started/try-falco/try-falcosidekick-on-kubernetes/index.md
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Fixes #1044 
=> fix(doc): missing step in try falco tutorial

assets/scss/_glossary.scss
> /kind bug
/kind design
> /area blog
> /area videos
Fixes #
=> change style for glossary tooltip links

content/en/blog/adaptive-syscalls-selection/index.md, content/en/blog/falco-detect-cryptomining/index.md, content/en/blog/falco-kind-prometheus-grafana.md, content/en/blog/restructuring-the-kubernetes-threat-matrix/index.md, content/en/docs/event-sources/sample-events.md, content/en/docs/plugins/developers-guide/_index.md, content/en/docs/plugins/developers-guide/how-to-develop.md, content/en/docs/plugins/developers-guide/how-to-distribute.md, content/en/docs/plugins/developers-guide/how-to-register.md, content/en/docs/reference/daemon/config-options/index.md, content/en/docs/reference/plugins/go-sdk-walkthrough.md, content/en/docs/reference/plugins/plugin-api-reference.md
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Fixes #
=> fix(docs): aliases fixed for some documentation links

content/en/about/use-cases.md, data/en/features.yaml, data/en/usecases.yaml, i18n/en/en.yaml
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
See #1003 
Fixes #
=> docs: finalize the definition for Falco

content/en/docs/rules/_index.md, content/en/docs/rules/versioning.md
/kind content
This PR adds cross-referencing to the rules repository from the appropriate documentation pages.
Fixes #
=> update(docs): update repo/website cross referencing for rules

.github/PULL_REQUEST_TEMPLATE.md
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
This change facilitates the use of kind/event and area/community labels, and it removes the area/videos label suggestion that hasn't been used until the moment.
=> add kind/event and replace area/videos with area/community

content/en/docs/event-sources/kernel/_index.md, content/en/docs/event-sources/kernel/dropped-events.md, content/en/docs/event-sources/kernel/sample-events.md, content/en/docs/event-sources/plugins/kubernetes-audit.md, content/en/docs/grpc/_index.md, content/en/docs/grpc/grpc-config.md, content/en/docs/rules/appending.md, content/en/docs/rules/conditions.md, content/en/docs/rules/controlling-rules.md, content/en/docs/rules/default-custom.md, content/en/docs/rules/exceptions.md, content/en/docs/rules/special-characters.md, content/en/docs/rules/versioning.md
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Fixes #
=> refer to terms in the glossary

content/en/docs/rules/style-guide.md
> /kind bug
/kind cleanup
> /kind design
> /kind event
> /area blog
@leogr addressing feedback we missed.
Fixes #
=> cleanup: minor adjustments to style guide

README.md
/kind cleanup
While the website is linked in the sidebar, having it in the first line of the documentation won't hurt because that's where everyone looks
Fixes #
=> update(readme): add explicit link to the website

content/en/about/_index.md
/kind cleanup
For messaging consistency
=> Update _index.md with new messaging

content/en/docs/getting-started/kubernetes-quickstart.md, content/en/docs/getting-started/linux-quickstart.md
> /kind bug
> /kind design
/kind content
> /kind event
> /area blog
Fixes #
=> updating minor details and fixing typos

content/en/docs/_index.md, content/en/docs/rules/custom-ruleset.md, content/en/docs/rules/default-custom.md
/kind content
This PR adds instructions about how to configure your rules, plus better mentions for falcoctl, which is the preferred tool to update rules and plugins. While the plugin section already mentions it, the rules section did not and so here it is added.
Fixes #
=> update(content): add instructions for installing rules and falcoctl mentions

content/en/docs/rules/style-guide.md
> /kind bug
/kind cleanup
> /kind design
> /kind event
> /area blog
Enhance info wrt output fields in style guide to be able to point to agreed upon criteria when cleaning up existing rules now as well as maintaining them going forward. And of course, as criteria for new rules.
@leogr @LucaGuerra @vjjmiras ty!
Fixes #
=> cleanup: enhance info wrt output fields in style guide

content/en/docs/rules/style-guide.md
> /kind bug
> /kind design
/kind content
> /kind event
> /area blog
Small follow up to https://github.com/falcosecurity/falco-website/pull/1094 @leogr @LucaGuerra 
Fixes #
=> cleanup: adjust output fields in style guide

content/en/about/case-studies/r6-security/index.md
> /kind bug
> /kind design
/kind content
> /kind event
> /area blog
Fixes #
=> fix(case-study): missing word in R6 Security case study

content/en/docs/rules/adoption-rules.md
> /kind bug
> /kind design
/kind content
> /kind event
> /area blog
@leogr @LucaGuerra @vjjmiras 
Highly recommend adding such a guide to complete the big picture.
Fixes #
=> new: add dedication rules adoption in production guide

content/en/docs/install-operate/installation.md
> /kind bug
> /kind design
/kind content
> /kind event
> /area blog
Fixes #976
=> update(docs): add instructions for systemctl

content/en/docs/getting-started/linux-quickstart.md
/kind cleanup
I added cleanup instructions for the linux lab and made some edits to make it consistent with the Kubernetes lab. 
Fixes #
=> added cleanup instructions, fixed formatting for consistency

content/en/docs/install-operate/deployment.md, content/en/docs/install-operate/download.md, content/en/docs/install-operate/installation.md, content/en/docs/install-operate/running/index.md, content/en/docs/install-operate/upgrade.md
> /kind bug
/kind cleanup
> /kind design
/kind content
> /kind event
> /area blog
Fixes #
=> cleanup: add info to install and operate guides to improve clarity for adoption in production

config/_default/config.toml
/kind cleanup
Update the header button to reflect the content of the use cases page.
=> cleanup(docs): update tagline of about page

content/en/docs/getting-started/_index.md
> /kind bug
> /kind design
/kind content
> /kind event
> /area blog
Fixes #
=> fix(docs): update href to falco architecture image

content/en/blog/adaptive-syscalls-selection/index.md
/kind content
/area blog
Add tracker to lab link on the adaptive-sycall blog
=> Add tracker to lab link on the adaptive-sycall blog

data/en/events.yaml
> /kind bug
> /kind design
/kind event
> /area blog
Fixes #
=> update(events): new workshop dates for Autum

data/en/events.yaml
> /kind bug
> /kind design
/kind event
> /area blog
Fixes #
=> fix(event): removed cancelled workshops

content/en/docs/install-operate/installation.md, content/en/docs/tutorials/_index.md, content/en/docs/tutorials/add-prebuilt-driver-config/index.md
/kind content
This PR adds documentation for adding configuration for prebuilt driver.
Furthermore, it adds a troubleshooting section in the install page, with a specific sub-section about missing prebuilt drivers.
Fixes #980
NA
=> Add install troubleshooting and tutorial for adding driver build configs

content/en/blog/falcoctl-gitlab-oci-artifacts-support.md
/area blog
/cc @eminaktas
Fixes #1123 
=> add falcoctl gitlab oci artifact supports

content/en/docs/rules/style-guide.md
> /kind bug
/kind cleanup
> /kind design
> /kind event
> /area blog
Minor updates to the rules style guide. Do we need more updates from your perspective @leogr. Thanks for your feedback in advance! 
Fixes #
=> cleanup: update rules style guide

data/en/events.yaml
> /kind bug
> /kind design
/kind event
> /area blog
Fixes #
=> update(events): adding events in Europe

content/en/docs/rules/conditions.md
> /kind bug
> /kind design
/kind content
> /kind event
> /area blog
Fixes #
=> fix(docs): add explaination for set operations

config/_default/config.toml, content/en/about/case-studies/_index.md, content/en/about/ecosystem.md
> /kind bug
> /kind design
/kind content
> /kind event
> /area blog
Fixes #
=> add(about): landing page for case studies

data/en/events.yaml
> /kind bug
> /kind design
/kind content
> /kind event
> /area blog
Fixes #
=> add event in Paris Sept 2023

data/en/events.yaml
/kind event
Removed old events, added new virtual workshop, updated data on a few others. 
=> updated events

config/_default/versions/params.yaml
> /kind bug
/kind cleanup
> /kind design
> /kind event
> /area blog
As per title. Following the release process (post-release actions).
Fixes #
=> chore(docs): update config for Falco 0.36.0

assets/scss/_utilities.scss, config/_default/versions/params.yaml, content/en/docs/reference/rules/default-rules/index.md, content/en/docs/rules/default-custom.md, layouts/shortcodes/rules_list.html
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Fixes #
=> add default rules list

content/en/docs/event-sources/kernel/_index.md
/kind content
This PR  deprecates `--userspace` instrumentation
=> [0.36] content: deprecate `--userspace` instrumentation

content/en/blog/falco-0-36-0/index.md
/kind content
/area blog
fix breaking changes section in Falco 0.36.0 blog post
=> fix(content): fix breaking changes section in Falco 0.36.0 blog post

content/en/docs/outputs/forwarding.md
> /kind bug
> /kind design
/kind content
> /kind event
> /area blog
Add the list of available outputs in falcosidekick
Fixes #
=> add the list of outputs for falcosidekick

content/en/blog/falco-0-36-0/index.md
/kind bug
/area blog
as per title
Fixes #
=> fix(blog): fix typos/ambiguous sentence in 0.36.0 blog

Makefile, netlify.toml
> /kind bug
/kind cleanup
> /kind design
> /kind event
> /area blog
Fixes #
This PR aims to fix #1172 for future versions of the archiving process. However, some changes will need to be applied on the archived branches specifically.
=> fix: add environment separation for development and archived branches

Makefile, netlify.toml
/kind bug
> /kind design
> /kind event
> /area blog
Fixes #
#1172 for branch v0.35
=> unset production environment for archived branch v0.35

Makefile, netlify.toml
/kind bug
> /kind design
> /kind event
> /area blog
Fixes #
=> unset production environment for archived branch 0.33

Makefile, netlify.toml
/kind bug
> /kind design
> /kind event
> /area blog
Fixes #
=> unset production environment for archived branch 0.32

Makefile, netlify.toml
/kind bug
> /kind design
> /kind event
> /area blog
Fixes #
=> unset production environment for archived branch 0.34

themes/falco-fresh/layouts/partials/meta.html
/kind bug
> /kind design
> /kind event
> /area blog
Fixes #
=> set noindex and nofollow for archived branch 0.26

content/en/blog/falco-0-36-1/index.md
/kind content
/area blog
Add a blog post for Falco 0.36.1
=> new(blog): add a blog post for Falco 0.36.1

config/_default/versions/params.yaml
/kind design
update version number to 0.36.1
=> update(config): update version number to 0.36.1

config/_default/versions/params.yaml, content/en/blog/falco-0-36-2/index.md
=> new(content): added Falco 0.36.2 blog post.

data/en/events.yaml
This PR removes the previous events and adds the new ones.
Signed-off-by: Pablo Musa pablo.musa@sysdig.com
/kind event
=> Update the events page with the latest dates.

content/en/blog/new-cncf-lf-training/index.md
This PR fixes a typo in the training announcement blog.
/kind content
/area blog
=> [blog-new-training] fix typo

content/en/blog/falco-week-46.md
/kind content
/area blog
This PR adds the first of the weekly series of blog post about what's happening in Falco.
Fixes #
=> new(content): added  blog post for week #46 highlights.

content/en/blog/falco-week-47.md
/kind content
/area blog
Fixes #
=> new(content): added Falco weekly higlhlight for week 47.

OWNERS
As mentioned in the community call on Oct 25th I would like to help with the website repo maintenance
Fixes #
=> vote: update(OWNERS): add myself as an approver

content/en/blog/falco-week-48.md
/kind content
/area blog
Fixes #
=> new(content): Added Falco weekly 48.

content/en/blog/falco-okta-identity/index.md
This PR updates a fuzzy sentence in the okta blog. (cc: @n1g3ld0ugla5)
I also think that the block about Running Falco with Docker is out of scope and moves away from the main topic. I suggest removing it. Let me know if I should update the PR with that change.
/kind bug
/kind content
/area blog
=> [okta-blog] Update fuzzy sentence

content/en/docs/event-sources/kernel/_index.md
/kind bug
fix a broken link in the modern bpf section
=> fix: fix a broken link in the modern bpf section

content/en/docs/install-operate/running/index.md
Update the website to add missing options, to solve issues for users to run falco agent in containers. 
> /kind bug
> /kind design
> /kind event
> /area blog
https://github.com/falcosecurity/falco/issues/2990#issuecomment-1883470260
https://github.com/falcosecurity/falco/issues/2990
Fixes #
=> adding the missing /etc:/host/etc:ro for modern-bpf

content/en/blog/falco-week-3-2024/index.md, content/en/blog/falco-week-46-2023/index.md, content/en/blog/falco-week-47-2023/index.md, content/en/blog/falco-week-48-2023/index.md, content/en/blog/falco-week-50-2023/index.md
/kind content
/area blog
This PR adds a new weekly blog for week 3 2024 
=> new(blog): add new weekly blog for week 3 2024 

content/en/docs/outputs/formatting.md, content/en/docs/rules/style-guide.md
> /kind bug
/kind cleanup
> /kind design
> /kind event
> /area blog
refactor: update style guide and rewrite output formatting page
CC @Andreagit97 and @LucaGuerra @leogr thanks!
Fixes #
=> refactor: update style guide and rewrite output formatting page

content/en/docs/getting-started/linux-quickstart.md
> /kind bug
/kind cleanup
> /kind design
/kind content
> /kind event
> /area blog
correct 1-char typo in the word `Examine` previously spelt `Exmamine`
Fixes #
=> correct 1-char typo in the word Examine

content/en/blog/falco-m1.md
> /kind bug
> /kind design
/kind content
> /kind event
> /area blog
Minor adjustments to the Apple Silicon Guide. Outline emulated VM options for completeness.
Fixes #
=> update: add x86_64 emulated VM option to apple silicon guide

content/en/docs/install-operate/installation.md
> /kind bug
/kind cleanup
> /kind design
/kind content
> /kind event
> /area blog
I've reopened #1203 here, since it is blocked by a stale change request.
Fixes #
=> See PR 1203

config/_default/versions/params.yaml
=> chore(config): update website version

content/en/docs/reference/daemon/cli-arguments/cli-arguments.md
/kind content
This PR updates the CLI arguments for Falco 0.37.0
=> update(docs): update CLI args for Falco 0.37.0

content/en/blog/falco-0-37-0/index.md
/kind content
/area blog
fix indentation in Falco 0.37.0 blog post
=> cleanup(blog): fix indentation in Falco 0.37.0 blog post

content/en/docs/reference/rules/supported-fields/supported-fields.md
/kind content
update k8s fields description
=> update(docs): update k8s fields description

content/en/docs/install-operate/source.md
/kind cleanup
Update the build from source documentation to Falco 0.37.0. I have tested many build paths and it looks like they are working. Also, please see inline comments.
Fixes #1091
=> update(docs): update build from source page

content/en/blog/falco-0-37-1/index.md
/kind content
/area blog
Fixes #
=> new(content): added blog post for Falco 0.37.1 patch release.

content/en/docs/install-operate/running/index.md
=> chore(docs): falco-no-driver still needs etc volume.

content/en/blog/falco-week-7-2024/index.md
/kind content
/area blog
Fixes #
=> new(content): added weekly recap w7 2024.

layouts/_default/baseof.html, layouts/blog/baseof.html, layouts/docs/baseof.html
/kind bug
/kind cleanup
> /kind design
> /kind event
> /area blog
Fixes #
=> fix(layouts): footer spacing

layouts/shortcodes/rules_list.html
> /kind bug
/kind cleanup
> /kind design
> /kind event
> /area blog
All rules are now referenced with an anchor, which allow to share a direct link to every of them
Fixes #
=> add anchors to allow to share a rule with a link

data/videos.yaml
> /kind bug
> /kind design
/kind content
> /kind event
> /area blog
Change the plugged video in the main page
Fixes #
=> update plugged videos in landing page

content/en/about/_index.md, i18n/en/en.yaml, i18n/ja/ja.yaml, i18n/ko/ko.yaml, i18n/zh-cn/zh-cn.yaml, layouts/community/falco-brand.html
/kind content
Update CNCF project status
Fixes #
=> update(content): incubating->graduated

content/en/blog/falco-graduation/index.md
/kind bug
/area blog
Fix the metadata link
Fixes #
=> fix(blog): falco graduation image metadata

content/en/docs/metrics/falco-metrics.md
> /kind bug
/kind cleanup
> /kind design
/kind content
> /kind event
> /area blog
Add notice of few metric names changes for Falco 0.38.0.
@leogr 
Fixes #
=> cleanup: add notice of few metric names changes for Falco 0.38.0

content/en/about/case-studies/incepto-medical/index.md, content/en/about/case-studies/r6-security/index.md
> /kind bug
/kind cleanup
> /kind design
> /kind event
> /area blog
Fixes #
=> remove useless titles

content/en/blog/falco-week-10-2024/index.md
/kind content
/area blog
Fixes #
=> new(content): added falco weekly 10 2024 blog post.

content/en/docs/install-operate/running/index.md
/kind bug
As per title. Fix the example command. Thanks @terylt and Ramesh N from the Falco slack for spotting the issue.
Fixes #
=> fix(docs): fix run eBPF Docker command

config/_default/config.toml, content/en/docs/roadmap.md
/kind content
As per title.
Fixes #
=> new(docs): add roadmap page

content/en/blog/falco-network-security/index.md
> /kind bug
> /kind design
> /kind event
/area blog
Fixes #
=> Falco network security

content/en/docs/getting-started/linux-quickstart.md
/kind cleanup
See issue https://github.com/falcosecurity/falco-website/issues/1310
Fixes #1310
=> fix(docs): fix example command indentation

content/en/docs/install-operate/third-party/learning.md
> /kind bug
> /kind design
/kind content
> /kind event
> /area blog
This PR updates the minikube docs. 
Changes:
* use only the modern ebpf probe;
* use preset values file for syscall + k8saudit sources.
Fixes #
=> update(learning/minikube): update minikube tutorial

data/en/announcements/announcement.yaml, data/en/announcements/graduation.yaml, data/en/announcements/kubecon-eu.yaml
/kind cleanup
As per title
Fixes #
=> update(docs): remove all announcements

config/_default/versions/params.yaml
/kind cleanup
As per title
Fixes #
=> update(config): configure for 0.38.0

content/en/docs/rules/basic-elements.md, content/en/docs/rules/conditions.md
> /kind bug
> /kind design
> /kind event
Document new conditions/output operators in Falco 0.38.0
Fixes #
=> new(docs): add docs for transform operators and val()

content/en/docs/rules/controlling-rules.md
/kind content
Document this: https://github.com/falcosecurity/falco/pull/3178
Fixes #1316
=> new(docs): add rule selection documentation

content/en/docs/reference/daemon/config-options/index.md
/kind content
Documenting new changes in the `falco.yaml` config file and `-o` options. Also, removing the outdated table while we think what do to with it.
Fixes #
=> update(content): add documentation on subkey new items and config_files

content/en/docs/metrics/falco-metrics.md
> /kind bug
> /kind design
/kind content
> /kind event
> /area blog
Update example metrics outputs for Falco 0.38.0.
Fixes #
=> cleanup(metrics): update example outputs for falco 0.38.0

content/en/blog/falco-0-38-1/index.md
/kind content
/area blog
Fixes #
=> new(content): added Falco 0.38.1 blog post.

config/_default/versions/params.yaml
=> chore(config): update Falco version number for 0.38.1

content/en/docs/getting-started/kubernetes-quickstart.md
Fixes #1337 
As discussed in that issue, this PR switches the quickstart to using `modern_ebpf`. I can also change other references in the documentation as part of this PR if you want me to.
=> Change driver mention in Kubernetes quickstart to modern_ebpf

content/en/docs/outputs/forwarding.md
> /kind bug
> /kind design
/kind content
> /kind event
> /area blog
Fixes #
=> add new outputs for falcosidekick 2.29

content/en/blog/falco-0-38-2/index.md
/kind content
/area blog
Blog for the 0.38.2 patch release
Fixes #
=> new(blog): add falco 0.38.2 blog

content/en/docs/metrics/falco-metrics.md
> /kind bug
/kind cleanup
> /kind design
/kind content
> /kind event
> /area blog
Describe prometheus metrics changes for Falco 0.38.2. Plus added a few sentences in here and there to create a clearer doc.
@Issif @LucaGuerra @sgaist thanks.
Fixes #
=> update(metrics): describe prometheus metrics changes for Falco 0.38.2

config/_default/versions/params.yaml
/kind content
as per title
Fixes #
=> update(config): add 0.38.2

content/en/docs/getting-started/linux-quickstart.md
/kind content
This PR updates the Linux quickstart tutorial to work with Ubuntu 24.04 virtual machines. Moreover, it corrects some version discrepancies throughout the document. 
Fixes #
=> update(docs): update Linux quickstart tutorial to work with Ubuntu 24.04

content/en/docs/getting-started/additional-resources.md, content/en/docs/getting-started/learning-environments.md
> /kind bug
> /kind design
/kind content
> /kind event
> /area blog
This PR fixes a typo in Plugin spelling and removes duplicate microK8s getting started link
Fixes #
=> fix(docs): fix a typo and remove duplicate microK8s getting started link

content/en/docs/setup/container.md
> /kind bug
> /kind design
/kind content
> /kind event
> /area blog
This PR fixes some minor formatting errors and the docker commands to run Falco in fully privileged mode.
Fixes #
=> fix(docs): fix setup on containerized environment

content/en/docs/setup/packages.md
> /kind bug
> /kind design
/kind content
> /kind event
> /area blog
This PR:
- moves some installation notes before the corresponding shell commands, in order to improve notes effectiveness
- fixes the description of the environment variables that can be provided during the package installation process
- add description for falcoctl dialog in package installation
- fixes some broken anchors and update manual configuration description
Fixes #
**Special notes for your …
=> fix(docs): fix package installation style and description

content/en/docs/rules/exceptions.md
> /kind bug
> /kind design
/kind content
> /kind event
> /area blog
This PR fixes some minor typos and the style on rules exception documentation. Moreover, it updates the exceptions overriding documentation to the new technique based on the `override` section.
Fixes #
=> fix(docs): fix rules exceptions doc typos and style and update to new override technique

content/en/docs/outputs/_index.md, content/en/docs/outputs/channels.md
> /kind bug
> /kind design
/kind content
> /kind event
> /area blog
This PR fixes some typos and style in outputs channel documentation.
Fixes #
=> fix(docs): fix typos and style in outputs doc

config/_default/versions/params.yaml
/kind content
As per release process
Fixes #
=> chore(website): update to version 0.39.0

content/en/docs/metrics/falco-metrics.md
> /kind bug
/kind cleanup
> /kind design
> /kind event
> /area blog
Fixes #1368
=> update(falco-metrics): falco metrics 0.39.0

content/en/docs/rules/conditions.md
/kind content
> /kind event
As per title.
Fixes #1360, #1361
=> new(docs): add regex and basename documentation

content/en/docs/reference/rules/supported-events/supported-events.md, content/en/docs/reference/rules/supported-fields/supported-fields.md
> /kind bug
> /kind design
> /kind event
> /area blog
Fixes #
=> update(docs): update supported events and fields for Falco 0.39.0

content/en/docs/rules/controlling-rules.md
/kind cleanup
We have removed `-D`, `-t`, `-T` from Falco in version 0.39.0: https://github.com/falcosecurity/falco/pull/3311 . Remove them from the documentation as well.
Fixes #
=> update(docs): remove references to -D -T -t

config/_default/versions/params.yaml
/kind bug
oops (but in archive branch)
Fixes #
=> fix(config): typo (but in archive branch)

config/_default/versions/params.yaml
=> fix(config): typo

content/en/docs/metrics/falco-metrics.md
> /kind bug
> /kind design
/kind content
> /kind event
> /area blog
Fixes #
=> docs(content): update metrics to reflect 0.39 changes

content/en/blog/falco-0-39-1/index.md
/kind content
/area blog
Fixes #
=> new(content): blog post for Falco 0.39.1.

config/_default/versions/params.yaml
=> update(config): bump Falco version to 0.39.1.

content/en/blog/falco-k8smeta-plugin/index.md
> /kind bug
> /kind design
/kind content
> /kind event
/area blog
Fixes #
=> new(content/blog): add post about falco + k8s-metacollector + k8smeta

data/en/events.yaml
> /kind bug
> /kind design
/kind event
> /area blog
I am trying to add an upcoming event related to CNCF Live.
Fixes #
=> CNCF Live Upcoming Event Added to Events Page

content/en/docs/reference/rules/supported-fields/supported-fields.md
/kind bug
As per title. In all future versions of Falco `LIST()` items are marked automatically when generating this page.
Fixes #
=> update(docs): add list indication for list field

layouts/enterprise/enterprise.html
/kind bug
> /kind design
> /kind event
> /area blog
Fixes #
=> fix(layout/enterprise): style for mobile devices

config/_default/versions/params.yaml, content/en/blog/falco-0-39-2/index.md
/kind content
/area blog
Fixes #
=> new(content, config): Falco 0.39.2

content/en/blog/falco-0-39-2/index.md
/kind bug
> /kind design
> /kind event
/area blog
Fixes #
=> fix(blog/falco-0-39-2): update URLs and minor impr.

assets/scss/_pageinfo.scss, assets/scss/_tables.scss, config/_default/versions/params.yaml, content/en/docs/outputs/forwarding.md, layouts/shortcodes/plugins.html, layouts/shortcodes/rules_list.html
> /kind bug
/kind cleanup
/kind design
> /kind event
> /area blog
This PR introduces various fixes:
- update the shortcode for the list of plugins to be refreshed at each update of the website, the list is currently outdated
- fix the width of the tables to use all the space
- fix the width of the pageinfo to use all the space
- fix the versions for the rules files (they all now have different versions to track)
- update the list of ouputs of Falcosidekick
Before:
After:
Before:
After:
**Which issue(s) …
=> fix list of plugins + rules versions + width of pageinfo/tables

content/en/docs/plugins/architecture.md
/kind content
Mention Rust SDK in the Plugins page
Fixes #
=> update(docs): rust plugin sdk link

content/en/docs/plugins/developers-guide/how-to-distribute.md
Fixes "Checkout Falcoctl Repo" stage in the GitHub action.
=> Fix "Checkout Falcoctl Repo" stage in the GH action

content/en/docs/plugins/developers-guide/how-to-distribute.md
Fixe the runs-on field in the "release" stage
=> Fix the runs-on field in the "release" stage

content/en/docs/concepts/rules/_index.md, content/en/docs/concepts/rules/adoption-rules.md, content/en/docs/concepts/rules/basic-elements.md, content/en/docs/concepts/rules/conditions.md, content/en/docs/concepts/rules/controlling-rules.md, content/en/docs/concepts/rules/custom-ruleset.md, content/en/docs/concepts/rules/default-custom.md, content/en/docs/concepts/rules/exceptions.md, content/en/docs/concepts/rules/fd-sip-name.md, content/en/docs/concepts/rules/fspath.md, content/en/docs/concepts/rules/ide-support.md, content/en/docs/concepts/rules/overriding.md, content/en/docs/concepts/rules/pmatch-operator.md, content/en/docs/concepts/rules/special-characters.md, content/en/docs/concepts/rules/style-guide.md, content/en/docs/concepts/rules/versioning.md
/kind bug
Fix aliases in the `concepts/rules` section as they were not pointing to the right place. This allows links like https://falco.org/docs/rules/conditions/#operators to work again
Fixes #
=> fix(website): fix concept/rules aliases

README.md
> /kind bug
/kind cleanup
> /kind design
> /kind event
> /area blog
Fixes #
=> docs(README.md): add netlify deployment status

content/en/docs/concepts/event-sources/_index.md, content/en/docs/concepts/event-sources/gvisor/_index.md, content/en/docs/concepts/event-sources/kernel/dropped-events.md, content/en/docs/concepts/event-sources/kernel/sample-events.md, content/en/docs/concepts/event-sources/plugins/cloudtrail.md, content/en/docs/concepts/event-sources/plugins/kubernetes-audit.md, content/en/docs/concepts/event-sources/plugins/okta.md
/kind bug
> /kind design
/kind content
> /kind event
> /area blog
Fixes #
=>  fix(content/en/docs/concepts): url aliases

content/en/docs/concepts/rules/_index.md
/kind bug
> /kind design
> /kind event
> /area blog
as per title
Fixes #
=> fix(website): rules alias

content/en/docs/concepts/event-sources/kernel/_index.md
/kind bug
> /kind design
> /kind event
> /area blog
Caught by:
https://github.com/falcosecurity/charts/actions/runs/12826613509/job/35769986452?pr=813
Fixes #
=> fix(content): add missing redirects for `event-sources/kernel` page

netlify.toml
> /kind bug
/kind cleanup
> /kind design
> /kind event
> /area blog
We have this domain, but it has not yet been used. I have already configured it on Netlify, now this PR just add a redirect rule from https://falcosecurity.dev/ to https://falco.org
Fixes #
=> update(netlify.toml): add falcosecurity.dev domain (redirect)

config/_default/versions/params.yaml
> /kind bug
/kind cleanup
Config update
Fixes #
=> update(config): update for Falco 0.40.0

content/en/docs/concepts/outputs/formatting.md
> /kind bug
> /kind design
/kind content
> /kind event
> /area blog
Fixes #
/milestone falco-0.40.0
/hold for 0.40.0
=> docs(content): improve Alert Formatting and add `suggested_output`

content/en/blog/falco-aks-audit-logs-plugin/index.md
fix: broken links for AKS audit logs
=> fix: broken links for AKS audit logs

content/en/blog/detecting-supplychain-attacks-with-falco-action/index.md
> /kind bug
> /kind design
/kind content
> /kind event
/area blog
New blog post about using Falco Actions to detect supply chain attacks
Fixes #
=> Add blog post on Falco Actions to detect supply chain attacks

content/en/docs/concepts/outputs/forwarding.md
Smoothed out the second sentence for better readability.
> /kind bug
> /kind design
> /kind event
> /area blog
Fixes #
=> Smoothed out the second sentence for better readability

release.md
/kind cleanup
This adds the commands to update event and field list explicitly in the readme.
Fixes #
=> update(docs): include field/event update in the release document

content/en/blog/falco-0-41.0/index.md
/kind content
/area blog
Fixes #
=> new(content): added Falco 0.41.0 blog post.

content/en/docs/concepts/metrics/_index.md
> /kind bug
/kind cleanup
> /kind design
> /kind event
> /area blog
update(metrics): sync page for Falco 0.41.0 release
Fixes #
=> update(metrics): sync page for Falco 0.41.0 release

content/en/docs/concepts/event-sources/plugins/kubernetes-audit.md, content/en/docs/reference/plugins/plugin-api-reference.md
> /kind bug
/kind cleanup
> /kind design
/kind content
> /kind event
> /area blog
Addresses some more typos in the documentation.
N/A
=> update(docs): address typos

config/_default/versions/params.yaml
> /kind bug
> /kind design
/kind content
> /kind event
> /area blog
This PR adds support for Falco version 0.41.2 and incubating/sandbox rules version 5.0.1.
Fixes #
=> update: versions/params.yaml to Falco 0.41.2 and latest rules versions

config/_default/versions/params.yaml
> /kind bug
> /kind design
/kind content
> /kind event
> /area blog
This PR adds support for Falco version `0.41.3`.
Fixes #
=> update: versions/params.yaml to Falco 0.41.3 and latest rules versions

content/en/docs/developer-guide/source.md
> /kind bug
> /kind design
/kind content
> /kind event
> /area blog
Fixes #
=> update(content): add `bpftool` dep for install instructions on debian

content/en/blog/intro-gvisor-falco/index.md, content/en/docs/concepts/event-sources/gvisor/_index.md
> /kind bug
/kind cleanup
> /kind design
> /kind event
> /area blog
There's a slight typo in the gVisor documentation. This is a simple PR to improve it.
The word permanent was misspelled as permament.
=> Fixed typos in the gVisor documentation
