- config.yaml
This PR updates the Hugo configuration to publish to the default `public` directory (rather than using a separate repo for GitHub Pages) and disables taxonomies (which currently aren't being used by the site).
> Update Hugo configuration

- content/docs/configuration.md
- data/config.yaml
- themes/falco-fresh/layouts/partials/docs/article.html
- themes/falco-fresh/layouts/shortcodes/config.html
This PR converts the configuration doc to a table generated via a `config.yaml` file. This should make the presentation more compact and the configuration documentation more maintainable.
https://deploy-preview-8--falcosecurity.netlify.com/docs/configuration/
> Convert configuration doc to table

- content/docs/event-sources/kernel-module.md
Simple typo fix for docker image name - thanks!
> Fix typo in docker image name

- config.yaml
- content/docs/installation.md
- themes/falco-fresh/layouts/shortcodes/md5sum.html
This PR enables you to set the expected md5sum in the site's configuration rather than needing to hard-code it in Markdown.
The `md5sum` shortcode can also be re-used anywhere in the documentation in the future.
Also, @mfdii, the current checksum seems to be incorrect if I'm not mistaken. Should we update? I'm getting `228e1a9002f5d00dc40fafe13b1bd1ab` from the downloadable script.
> Add md5sum shortcode

- content/docs/installation.md
Improve install docs by doing the following:
- Move Kubernetes docs to top. 
- better description of what's happening with the kernel module at pod start
- instructions to pull the KM via HTTPS
- Helm instructions (WIP)
- Include KRE summary and point to helm docs on how it enable
- Move daemonset instructions to install docs
- Include GKE "gotchas" section (WIP)
- Move host based install and cfg mgmt install to bottom
- Improve host based install and cfgmgt install docs (WIP)
Signed-off-by: Michael Ducy <michael@ducy.org>
> Fix installation docs to include better install instructions

- content/docs/installation.md
On some user agents linking an anchor using another case (eg., uppercase) does not work (more details [here](https://www.w3.org/TR/html401/struct/links.html#h-12.2.1)). This PR aims to fix the link to use the lowercase one.
Fixes #45
> fix(installation): gke link

- content/cheatsheet/forbidden-thing.yaml
- content/cheatsheet/other-thing.yaml
- content/docs/cheatsheet.md
- data/cheatsheet.yaml
- themes/falco-fresh/assets/cheatsheet.sass
- themes/falco-fresh/assets/style.sass
- themes/falco-fresh/layouts/shortcodes/cheat.html
- themes/falco-fresh/layouts/shortcodes/cheatsheet.html
Addresses issue #42. With these changes, you can add a "cheat" for the cheatsheet by:
1. Adding an entry to `data/cheatsheet.yaml`
1. Adding a YAML file in `docs/cheatsheet` with the example YAML (the filename must correspond to the key in `data/cheatsheet.yaml`)
You can see the very basic example at https://deploy-preview-49--falcosecurity.netlify.com/docs/cheatsheet.
There are a lot of directions this could be taken. The cheats could be divided into groups, etc.
> Provide cheatsheet scaffolding

- themes/falco-fresh/layouts/partials/navbar.html
Someone changed the base URL in the navbar to `/{language}`. That system will not work until we have multiple languages working on the site. For now it 404s.
> Fix home link

- content/en/docs/changelog.md
- themes/falco-fresh/layouts/shortcodes/changelog.html
/kind content
This PR provides a new Hugo shortcode for creating a changelog page into /docs section. Each time the website is "built", the shortcode calls github API to gather all releases and generates a full changelog page. No need to update a variable.
N/A
N/A
> add a shortcode + doc page to display changelog from github releases

- config.yaml
- netlify.toml
- themes/falco-fresh/layouts/partials/docs/dashboard.html
Documentation header indicates latest available release, this needed to be manually updated in site parameters. Not it uses github's API to retrieve last release tag and complete header. Only need to rebuild site to be up to date.
N/A
N/A
> latest release tag is auto-gathered

- content/en/docs/grpc/_index.md
- content/en/docs/grpc/client-go.md
There's nothing wrong with using Hugo's `{{< highlight >}}` shortcode for syntax highlighting, and there are even cases where it's necessary, but when you do so you lose (a) text editor compatibility, and (b) highlighting on GitHub.
> Use backtick-based highlighting

- content/en/docs/psp_support/_index.md
Add docs describing the changes in https://github.com/falcosecurity/falco/pull/826.
> /kind bug
> /kind design
/kind content
> /area blog
Add docs for K8s PSP Support.
Fixes #
> Add docs for K8s PSP Support

- content/en/docs/installation.md
Signed-off-by: James Naftel <james.naftel@gmail.com>
/kind bug
> /kind design
/kind content
> /area blog
I was working through the installation instructions and noticed that the label seems to be wrong for viewing logs through kubectl.
Step 7 under daemonsets.
Fixes #
> fix: wrong label for viewing logs

- config.yaml
I don't know when these got out of sync. I wasn't able to find the git
repo holding the installer script to verify.
/kind cleanup
The sha256sum of the `curl | bash` install script has diverged from the text on the website. This fixes that.
I wasn't able to find the upstream source of the installer script. It would be good to know what changed in the script to cause the sha to change just for peace of mind.
> Update sha256sum for curl | bash installer

- content/en/docs/installation.md
- content/en/docs/source.md
This PR follows up on #147 and uses the `latest` shortcode to dynamically insert the latest version. Make sure to use this method for version insertion in the future for the sake of maintainability.
> Use shortcodes for version insertion

- content/en/docs/rules/_index.md
/kind bug
Some links point to sysdig.org which is a squatted domain with malware. This fix replaces them by `.com` tld.
N/A
Fixes #
Thanks to [@thecodejunkie](https://github.com/thecodejunkie) for having pointed it.
> fix wrong tld for sysdig domain

- content/en/docs/event-sources/sample-events.md
Docs corresponding to the falco changes that add k8s resource files to
allow running the event generator in a k8s cluster.
> /kind bug
> /kind design
/kind content
> /area blog
Fixes #
Docs corresponding to the falco changes in https://github.com/falcosecurity/falco/pull/1088
> Docs describing k8s event generator yaml files

- content/en/docs/event-sources/kubernetes-audit.md
- content/jp/docs/event-sources/kubernetes-audit.md
The examples on k8s audit event sources moved from the main repo to the evolution one.
/kind content
> Fix old links to Kubernetes audit readme file

- content/en/docs/third-party.md
/kind bug
> /area blog
Change the Helm chart link to point to the Falco's chart directly.
It will help folks to find instruction easily. 
Fixes #
https://kubernetes.slack.com/archives/CMWH3EH32/p1591372966173800?thread_ts=1591369299.170300&cid=CMWH3EH32
/cc @kris-nova
> fix(docs): direct helm chart link

- data/en/config.yaml
- data/jp/config.yaml
/kind cleanup
/kind content
Fixes #
Refs to https://github.com/falcosecurity/falco/pull/1292 and https://github.com/falcosecurity/falco/pull/1261
> update: fix audit endpoint

- content/en/docs/running.md
/kind content
There was no reference to the `SKIP_MODULE_LOAD` within the documentation. Moreover, it was renamed to `SKIP_DRIVER_LOADER` recently (https://github.com/falcosecurity/falco/pull/1297); thus, it's time to mention it under the "Running" section of the official documentation.
Finally, I also added a reference to the `DRIVER_REPO` env var under the same section since it can be useful in the same context.
Fixes #
Since the renaming (`SKIP_MODULE_LOAD` :point_right: `SKIP_DRIVER_LOADER`) will be effective when Falco 0.24.0 is released, keep this on
/hold
until then. …
> update(content/en/docs/running): add `SKIP_DRIVER_LOADER` option

- config.yaml
Signed-off-by: Spencer Krum <nibz@spencerkrum.com>
/kind bug
> /kind design
> /area blog
We didn't bump the version in `config.yaml` so when someone is on our docs it looks like they're seeing the 0.23.0 version of the docs not 0.24.0/master.
Fixes #
I'll try to find where the release process docs are and add 'update config.yaml' in there.
> chore: bump falco version in docs

- themes/falco-fresh/layouts/_default/baseof.html
I noticed that every time I share a page of the website on the social media the title is always "The Falco Project" regardless the page.
With this PR I'm adjusting the things by:
- If it's home page, just input "The Falco Project"
- If it's the blog home page "All entries - The Falco Project"
- If it's an article or a page "Page title - The Falco Project"
Fixes #
> fix: template title to include the page title and not just the website title

- config.yaml
The reason why I'm featuring this talk is:
The Kubecon NA 2020 keynote is very representative of the current state
of art of Falco from an users point of view and also features an end
user use case from Shopify.
@kris-nova initially wanted to make this to the Falco home page too https://github.com/falcosecurity/falco-website/pull/251
/kind content
Fixes #
> update: make the kubecon keynote as featured

- content/en/docs/event-sources/kubernetes-audit.md
This was mentioned in slack today. The double pound sign makes the
subheading clickable/linkable.
Signed-off-by: Spencer Krum <nibz@spencerkrum.com>
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Fixes #
Was disucssed in slack
> docs: A small touchup on the kube audit docs

- content/en/docs/rules/_index.md
Signed-off-by: bluefriday <bluefriday86@gmail.com>
I found typo while translating into Korean.
> /kind bug
'Tthe' ->'The'
- https://falco.org/docs/rules/
> type correnction Tthe -> The in rule index file

- config.yaml
Signed-off-by: KeisukeYamashita <19yamashita15@gmail.com>
> /kind bug
/kind cleanup
> /kind design
> /area blog
> /area videos
Current name is GitHub(Ref: https://github.com/) with the capital H. 
I want to fix this to make document better 🙇 
Fixes #
> Fix typo "Github" to "GitHub"

- content/en/docs/getting-started/running.md
/kind bug
/kind content
> /area blog
> /area videos
This is needed once https://github.com/falcosecurity/falco/pull/1492 gets merged.
Fixes #
Do not merge before, since the docker sock path is related to the `HOST_ROOT` env variable that is currently missing in the falco-no-driver image as explained in https://github.com/falcosecurity/falco/issues/1491
/hold
> update(content/en): falco-no-driver example to work with new `HOST_ROOT` default

- content/en/docs/getting-started/running.md
/kind content
The "Run with Docker" examples for the "fully privileged" use case are missing `-v /var/run/docker.sock:/host/var/run/docker.sock`.
That should be present in those examples since it's a docker use case, and Falco uses container metadata by default.
Fixes #
> update(content/en): add docker sock in "Run within Docker" section

- content/en/blog/choosing-a-driver.md
- content/en/blog/cloud-native-security-hub.md
- content/en/blog/detect-cve-2020-8557.md
- content/en/blog/extend-falco-outputs-with-falcosidekick.md
- content/en/blog/falco-0-20-0.md
- content/en/blog/falco-0-21-0.md
- content/en/blog/falco-0-22-x.md
- content/en/blog/falco-0-23-0.md
- content/en/blog/falco-0-24-0.md
- content/en/blog/falco-0-25-0.md
- content/en/blog/falco-0-26-1.md
- content/en/blog/falco-0-26-2.md
- content/en/blog/falco-2020.md
- content/en/blog/falco-in-the-open.md
- content/en/blog/falco-kind-prometheus-grafana.md
- content/en/blog/falco-scope.md
- content/en/blog/falco-security-audit.md
- content/en/blog/falco-wsl2-custom-kernel.md
- content/en/blog/falcosideckick-joins-falcosecurity.md
- content/en/blog/falcosidekick-2020.md
- content/en/blog/falcosidekick-kubeless.md
- content/en/blog/intro-k8s-security-monitoring.md
- content/en/blog/minikube-falco-kernel-module.md
- content/en/blog/security-boundaries-with-systemd-and-kubernetes.md
/kind bug
/area blog
Fix an issue reported by @Issif on the slack channel where our new website blog urls are not matching the old website ones.
I had to add a specific slug for every old blog post to reflect what it had in the old blog because we already have the 0.27.0 release blog post out on social and because of that we now had two different schemes deployed.
I think this is also a good opportunity to remember that the `slug: ` tag exists in Hugo and that we can use that to create more friendly URLs instead of using what hugo gives.
> update: fix blog post slugs

- content/en/docs/event-sources/kubernetes-audit.md
Signed-off-by: Frank Jogeleit frank.jogeleit@web.de
/kind bug
/kind content
Users who copy paste this config argument can crash the kube-apiserver
Fixes #
The current name of the argument resulted in an cluster error. I found the corrent argument name in the kube-apiserver documentation.
> Fix "audit-webhook-config-file" argument name

- content/en/blog/exceptions.md
- content/en/blog/falco-0-21-0.md
- content/en/blog/falco-2020.md
- content/en/blog/falco-security-and-monitoring-on-rke-bare-metal-cluster-with-rancher.md
- content/en/blog/falco-wsl2-custom-kernel.md
- content/en/docs/getting-started/download.md
- content/en/docs/getting-started/installation.md
- content/en/docs/getting-started/upgrade.md
- content/ja/blog/exceptions.md
- content/ja/blog/falco-2020.md
- content/ja/blog/falco-wsl2-custom-kernel.md
- content/ja/docs/event-sources/kernel-module.md
- content/ja/docs/getting-started/download.md
- content/ja/docs/getting-started/installation.md
- content/ko/docs/download.md
- content/ko/docs/installation.md
- content/zh/docs/installation.md
- static/repo/falcosecurity-rpm-dev.repo
- static/repo/falcosecurity-rpm.repo
- static/script/install
/kind content
/area blog
This is part of the migration from Bintray to our in-house solution `download.falco.org`.
Also, it adds upgrade paths for Falco (as suggested by @fntlnz )
To be merged after https://github.com/falcosecurity/falco/issues/1567 has been completed.
/hold
/cc @fntlnz 
/cc @leodido
> Switch download links and packages repos to download.falco.org

- content/en/blog/falco-wsl2-custom-kernel.md
As written, the whole Linux kernel history will be cloned locally.  For our purposes, we only need the latest file versions (--depth 1) and a particular branch (--branch linux-rolling-stable).  This will save local storage space and network I/O.  My ISP appears to have started throttling me heavily in the middle of my full clone of the whole Linux kernel history.
Signed-off-by: Karl Magdsick <karl@magdsick.com>
/kind cleanup
This saves users time and space by only cloning the part of the Linux repository we need.
None
> Use git --depth and --branch flags to save space/time

- content/en/blog/contribution-drivers-kmod-ebpf-libraries.md
/kind cleanup
/area blog
Fixes the link to the libs contribution proposal.
NONE
/hold
until https://github.com/falcosecurity/falco/pull/1641 gets in.
> fix link to the libs contribution proposal

- content/en/blog/falcosidekick-reponse-engine-part-4-tekton.md
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
> /kind bug
I fixed some typos, and added necessary namespace information for RoleBinding to avoid an error like the following in for EventListener pod:
```bash
runtime/asm_amd64.s:1374: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: configmaps is forbidden: User "system:serviceaccount:falcoresponse:tekton-triggers-example-sa" cannot list resource "configmaps" in API group "" in the namespace "falcoresponse"
```
Fixes #
> fix some typos for falcosidekick-reponse-engine-part-4-tekton blog post

- config.toml
- release.md
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
This PR bumps the Falco version and adds a configuration for website snapshot of the previous version ( https://v0-28.falco.org/ ), as per [release instructions](https://github.com/falcosecurity/falco-website/blob/master/release.md#bump-the-version-on-the-current-website).
It also includes a small fix in the documentation.
Fixes #
> Update website to Falco version 0.29.0

- content/en/docs/getting-started/installation.md
Signed-off-by: Michele Zuccala <michele@zuccala.com>
/kind content
Our openSUSE installation steps have users install `kernel-default-devel`. This PR changes it to `kernel-devel-$(uname -r)` and provides some guidance on how to solve cases in which a package might have been removed from the upstream repo (like it's already being done for other distros in the same document - see CentOS as a reference).
N/A
> Docs: fix openSUSE install instructions

- content/en/docs/rules/fd-sip-name.md
Add additional docs on the implementation and use of
fd.sip.name/related fields in falco rules, as they behave differently
and users periodically have questions/problems using the fields.
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Fixes #
> Add docs on use of fd.sip.name/related fields

- config.toml
- static/script/install
- The script will install epel if not present
- The script will support Suse
- mobprobe command removed
- override instead of append to `falcosecurity.list` file.
I think that from version 0.28 a reload of the systemd manager configuration is needed.
Except for Suse (which we tested in our test environment, on different version of Suse) we used the script a lot without any issues.
Thanks for your time :)
/cc @leodido 
/cc @leogr 
/kind content
Signed-off-by: Domenico Chirabino
> Update install script

- content/en/docs/getting-started/third-party/production.md
Signed-off-by: ramshazar <1233515+ramshazar@users.noreply.github.com>
/kind cleanup
/kind documentation
There is a link on https://falco.org/docs/getting-started/third-party/production/#gke that is an 404.
The PR provides the correct link.
> fix link to Falco with helm

- content/en/docs/rules/supported-fields.md
This commit updates the old list of supported fields to consider the
ones we have now.
It also adds the commands to automatically generate the list for future
use or automation to avoid doing it manually.
e.g:
```
falco --list=syscall  |
sed -E 's/Field Class: (.*)/\n### Field Class: \1\n\n```/g' |
sed 's/----------------------/\n```/g'
```
/kind content
Fixes #
> docs: supported fields generated using commands and missing fields in list

- content/en/docs/getting-started/running.md
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
On Ubuntu 18.04.6 LTS, After installation, I had to enable the `falco` service first and then I could start it.
Otherwise, I was getting error: 
```
Failed to start falco.service: Unit falco.service not found
```
Fixes #
> Enable falco service

- content/en/docs/getting-started/deployment.md
/kind content
This adds a new docs section _Deployment_ nested under _Getting Started_. For now, this provides basic guidance to start deploying Falco in Kubernetes clusters. 
Additionally, this introduces a small note about the recent deprecation of Docker in Kubernetes and how Falco is affected by it.
> docs: add section about k8s deployment and the upcoming docker deprecation

- content/en/docs/rules/_index.md
Update the falco rules page with notes about rule event sources,
required_plugin_versions, and required_engine_versions.
Only required_plugin_versions is truly new with plugins, but all could
use some extra docs.
> /kind bug
/kind cleanup
> /kind design
> /area blog
> /area videos
Fixes #
> Small changes to rules page related to plugins/event sources

- content/en/docs/getting-started/running.md
> /kind bug
/kind cleanup
> /kind design
/kind content
> /area blog
> /area videos
`-v /dev:/host/dev` is not needed when using the eBPF probe. This PR modifies the provided instruction accordingly. 
Fixes #
TODOs:
> update: mouting /dev is not needed for eBPF

- content/en/docs/getting-started/running.md
- content/en/docs/plugins/developers-guide.md
Signed-off-by: Andrea Terzolo <andrea.terzolo@polito.it>
/kind bug
Typo in the `getting-started/running`  and  `/plugins/developers-guide` sections.
> fix: typo in the running and plugin dev-guide sections

- content/en/docs/getting-started/installation.md
Added an specific installation step for Amazlinux2
`amazon-linux-extras install epel`
kind content
area documentation
Just adding a particular step required by a specific Linux distribution (Amazon Linux 2)
Fixes #
> Update installation.md by adding an specific command for amzn2

- content/en/docs/getting-started/source.md
- content/ja/docs/getting-started/source.md
- content/ko/docs/source.md
- content/ml/docs/getting-started/source.md
> /kind bug
/kind cleanup
> /kind design
/kind content
> /area blog
> /area videos
Since Falco 0.30.0, `ncurses` is not required anymore.
See https://github.com/falcosecurity/falco/pull/1658
Fixes #
> docs(content): ncurses is not required anymore

- content/en/docs/getting-started/running.md
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
This PR tries to better describe how Falco can be run according to the least privileged principle. 
First, I removed the note stating that `--privileged` is required for Falco and eBPF. This is true in part. To be precise, on kernel versions <5.8 the `CAP_SYS_ADMIN` capability is required to perform the `bpf` syscall. The `--privileged` flag adds this capability under the hood, and that's why it works. However, that flag turns off …
> docs(content): improve doc on Falco least privileged with Docker container

- content/en/docs/getting-started/upgrade.md
Signed-off-by: Andrea Terzolo <andrea.terzolo@polito.it>
/kind content
When installing Falco with  `.deb`, `.rpm` or with the binary package, we have to remove the old kernel module injected in the kernel, before upgrading Falco. Otherwise, we will have errors like the following, due to driver versions incompatibility:
```
Runtime error: Kernel module does not support PPM_IOCTL_GET_API_VERSION. Exiting.
```
This happens with Falco `0.31.1` because we introduced a mechanism to detect incompatible driver versions. The simple command added here should solve issues with local package installations quoted here :point_down: …
> docs(content): add a new step in the upgrading phase

- content/en/docs/event-sources/_index.md
- content/en/docs/event-sources/cloudtrail.md
- content/en/docs/event-sources/okta.md
It mostly points to other repos/readmes/etc for the details on how to
use Cloudtrail with falco, but we didn't really have a docs page about
Cloudtrail other than inside the plugins section, which is too much
detail for someone just trying to get cloudtrail to work.
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Fixes #
> Add cloudtrail event source page

- content/en/docs/alerts/_index.md
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Add more explicit documentation on the behavior of the `-U/--unbuffered` option.
I think we need more documentation on that because in some clusters events might take a long time to appear in `kubectl logs -f` because of log output buffering. Although that is not the way people use to get falco logs in production it is the way some of us use to check if Falco is working, to do debugging, or …
> docs: add stdout buffering explanation

- content/en/blog/choosing-a-driver.md
/kind cleanup
/area blog
Updates minimum kernel version guidance to be 4.14. As per https://github.com/falcosecurity/libs/blob/master/driver/bpf/quirks.h#L14-L16 4.14 is the minimum kernel version
> fix: updating eBPF probe minimum kernel version guidance

- Makefile
According to documentation to run locally the website you should run:
`make serve`
This command fails on a clean checkout. The reason is that the submodule docksy has some submodules inside that aren't downloaded. Changed the submodule init to run recursively so that error doesn't happen.
/kind bug
> /kind design
> /area blog
> /area videos
Fixes #
> Fix first time make serve command fail due to not downloaded submodules

- content/en/docs/getting-started/third-party/production.md
Let users know about the CRI options (provided by @pabloopez) to use when using K3S
Original discussion is in here https://github.com/falcosecurity/falco/issues/1911
https://github.com/falcosecurity/falco-website/pull/560#pullrequestreview-994562513
> /kind bug
> /kind design
/kind content
Documentation
> /area blog
> /area videos
Let users know what parameters should be configured for CRI when using K3S.
The default setting used in Falco does not match the one used in K3S.
**Which issue(s) this PR …
> Display the CRI options where K3s is used

- content/en/docs/rules/conditions.md
Signed-off-by: Lorenzo Susini <susinilorenzo1@gmail.com>
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Add a description of [newly introduced](https://github.com/falcosecurity/libs/pull/172) `bcontains` and `bstartswith` operators.
Fixes #
> add `bcontains` and `bstartswith` to the table of operators

- data/en/config.yaml
Related to the changes in
https://github.com/falcosecurity/falco/pull/2098, update the docs for
the json_output config option to note that it controls both the output
format for falco alerts as well as the format of rules
loading/validation results.
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Fixes #
> Update docs for json_output option to reflect alerts+rules result

- content/en/docs/plugins/go-sdk-walkthrough.md
Signed-off-by: Matthew White <matthew.w.white@oracle.com>
/kind cleanup
/kind content
Corrects the link to the dummy plugin Go source code in the dummy walkthrough.
Fixes #
I'm assuming the entrypoint/main is correct for this, despite there being another `dummy.go` in the `pkg` directory.
> update(content/docs): correct dummy plugin Go source code link

- data/en/config.yaml
Related to the changes in
https://github.com/falcosecurity/falco/pull/2098, update the docs for
the json_output config option to note that it controls both the output
format for falco alerts as well as the format of rules
loading/validation results.
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Fixes #
> Update docs for json_output option to reflect alerts+rules result v2

- content/en/docs/rules/supported-fields.md
/kind cleanup
This syncs the list of supported fields (`syscall` source only) with the new list coming from Falco 0.33.0.
/hold until Falco 0.33.0 gets released
> update(content/en/docs): sync supported field list with Falco 0.33

- config/_default/config.toml
- config/_default/versions/params.yaml
- content/en/docs/supported-doc-versions.md
- i18n/en/supported-versions/en.yaml
- layouts/docs/supported-versions.html
- layouts/partials/docs/content-page.html
- release.md
This PR:
- Changes the order of how documentation versions are displayed under releases.
- Moves the configuration for that into a separate file, where all required changes take place when archiving.
- Adds an Available Documentation Versions page to display these inside the documentation.
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
> update(docs): version params

- content/en/docs/reference/_index.md
- layouts/partials/page-meta-links.html
This PR adds the possibility of adding the no_edit option in the FrontMatter section to hide the meta links on the right side.
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Fixes #
> new docs/reference section

- content/en/docs/getting-started/running/index.md
Signed-off-by: Lorenzo Susini <susinilorenzo1@gmail.com>
/kind bug
> /kind design
/kind content
> /area blog
> /area videos
There's no need for mounting the docker socket in falco driver loader
Fixes #
> fix: no need of docker socket in falco driver loader docs

- content/ko/docs/alerts/_index.md
- content/ko/docs/alerts/formatting.md
What type of PR is this?
/kind content
Any specific area of the project related to this PR?
What this PR does / why we need it:
Translate Translate docs/alerts into Korean
Which issue(s) this PR fixes:
Fixes #https://github.com/falcosecurity/falco-website/issues/805#issue-1573521157
Special notes for your reviewer:
@vjjmiras
> Translate docs/alerts/_index.md into Korean

- content/en/docs/rules/ide-support.md
Add a page noting editor support for falco rules files. Currently only flycheck-falco-rules for emacs.
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Now that the emacs syntax checker [flycheck-falco-rules](https://github.com/falcosecurity/flycheck-falco-rules) has been donated to falcosecurity and is available on MELPA (https://github.com/melpa/melpa/pull/8403), add a page about editor support for falco rules files and point to the flycheck-falco-rules repo.
**Which issue(s) …
> Add page for rules editor support

- content/en/docs/getting-started/installation.md
> /kind bug
/kind cleanup
> /kind design
> /area blog
> /area videos
This PR improves the Debian installation instructions as they are currently relying on a deprecated and soon to be removed tool (apt-key).
The refactored instructions follow best practice in terms of apt source handling to improve the system security as well as working as a power user rather than root.
Nothing particular
> fix: improve Debian instructions

- content/en/docs/getting-started/installation.md
/kind content
Given installation instructions don't work
Fixes #
* Adds missing "deb" type in apt source.list installation instruction
This PR fixes a syntax issue given in the documentation to install falco from apt source.list
> fix: added missing "deb" type in apt source.list

- content/en/blog/gitops-your-falco-rules/index.md
> /kind bug
> /kind design
/kind content
/area blog
> /area videos
Fixes #
> GitOps Falco Rules - wrong featured image path

- config/_default/versions/params.yaml
/kind cleanup
Sets the latest Falco version in the website. The previous version has been archived with a snapshot available at https://v0-34.falco.org and maintained in the [v0.34 branch](https://github.com/falcosecurity/falco-website/tree/v0.34).
> update(params.yaml): bump website to falco v0.35.0

- content/en/docs/getting-started/try-falco/try-falcosidekick-on-kubernetes/index.md
/kind content
- Removes the 'of' in the [0.1 Environment](https://falco.org/docs/getting-started/try-falco/try-falcosidekick-on-kubernetes/#0-1-environment) requirement description.
Fixes #1024 
- n/a
> Remove 'of' typo in Environment requirement

- data/en/reference/daemon/config_options.yaml
Add a clarifying blurb for `json_output` config option
Fixes #791
> fix #791 - json_output option influences --version output

- content/en/docs/alerts/_index.md
- content/en/docs/alerts/forwarding.md
- data/en/features.yaml
- layouts/partials/landing/features.html
/kind cleanup
Update the homepage and forwarding page to make it clearer, plus fix a typo in the alert link.
In addition, this adds an explicit link to the box in the homepage. This way it'll be much easier for users to find the right page that shows integration capabilities.
> update(docs): update alert forwarding page

- content/en/docs/reference/rules/supported-events/index.md
- content/en/docs/reference/rules/supported-events/supported-events.md
- content/en/docs/reference/rules/supported-fields/index.md
/kind cleanup
As written in issue 985, if you land in the supported fields page without noticing its sibling "supported events" page you might be left wondering what the events and the arguments actually are. This PR adds a link to make it clearer. In addition, I noticed that in one page the arguments were called "arguments" or "args" and in the other were called "params". Let's call them "arguments" (or args) in both pages for consistency.
Fixes #985
> update(supported events, supported fields): link the two pages together, fix ambiguous wording

- content/en/docs/install-operate/installation.md
This commit changes the command used to configure the apt repository. Instead of using `sudo cat` it uses `echo` + `sudo tee`. The current form doesn't work in Ubuntu if not run directly by root.
> /kind bug
> /kind design
/kind content
> /kind event
> /area blog
Fixes #1160
> fix(docs): changes cmd to configure apt repository

- content/en/docs/rules/fspath.md
Add a new page that describes how fs.path.* fields work, including the specific syscalls that are supported, which fields are mapped to fs.path.name/source/target, and an example rules file that takes advantage of the fields.
> /kind bug
> /kind design
/kind content
> /area blog
> /area videos
Fixes #
Corresponding code change PR: https://github.com/falcosecurity/libs/pull/1060
> Document fs.path.* fields

- content/ja/community/contributors.md
- content/ja/community/events.md
- content/ja/community/falco-brand.md
- content/ja/docs/reference
- content/ko/community/contributors.md
- content/ko/community/events.md
- content/ko/community/falco-brand.md
- content/ko/docs/reference
- content/ml/community/contributors.md
- content/ml/community/events.md
- content/ml/community/falco-brand.md
- content/ml/docs/reference
- content/zh-cn/community/contributors.md
- content/zh-cn/community/events.md
- content/zh-cn/community/falco-brand.md
- content/zh-cn/docs/reference
/kind bug
This comes from insight I got from @vjjmiras in https://github.com/falcosecurity/falco-website/pull/1155 . Since currently a bunch of pages are still redirecting to `ml` language, aliases in particular, I believe we need to fix that first.
Then, we have the problem that pages that do not have a translation will 404 on languages that are not English which I believe is a separate issues. In https://github.com/falcosecurity/falco-website/pull/1155 another trick was attempted by using `mounts` to fill in the gaps. That is however still a problem since …
> fix(content): remove en -> international links to pages

- content/en/docs/install-operate/third-party/learning.md
> /kind bug
> /kind design
> /kind event
> /area blog
This PR adds instructions to use `modern-bpf` probe in the Minikube tutorial. Since Minikube ships with recent kernels, the `modern-bps probe` should be used. No need for precompiled` kernel module` or `bpf probe.` 
Fixes #
> update(learning/minikube): add instructions to use modern-bpf probe

- content/en/blog/falco-performance-testing.md
- content/en/docs/grpc/grpc-config.md
- content/ja/blog/falco-performance-testing.md
- content/ml/docs/grpc/_index.md
- data/en/reference/daemon/config_options.yaml
> /kind bug
/kind cleanup
> /kind design
> /kind event
> /area blog
The default grpc unix socket path was changed in 0.33.0 from `/var/run/falco.sock` to `/run/falco/falco.sock` and there were still  some stale references to the old socket name.
Fixes #
> fix(docs): update grpc output socket name

- content/en/docs/install-operate/running/index.md
The existing privileged docker command for running ebpf incorrectly tries to load the kmod, while running falco in ebpf mode.  By adding an environment variable we force the container to load the ebpf probe.  The command was also missing the `falco` cli.
/kind bug
It fixes the docker command for loading the ebpf version of falco.  The current command errors in two ways:
1. Since it doesn't have `falco` in it, docker incorrectly thinks the executable is `-o`
2. The docker container loads the kmod probe, but falco is loaded in `ebpf` mode.
Fixes #
> update(docs): fixed command for running privileged ebpf falco docker.

- content/en/docs/install-operate/source.md
/kind cleanup
The instructions about not using bundled deps were true before Ubuntu 18.04, so 14.04. That version is EOL'd and in order to have a better (if slower) experience we need to use bundled deps on all next versions. This updates the docs.
Fixes #
> fix(docs): update build instructions for Ubuntu

- content/en/blog/falco-m1.md
Using `driver.kind=modern-bpf` instead of `driver.kind=bpf` resolves the issue like this:
```Error: BPF probe is compiled for 5.15.0-100-generic-64k, but running version is 5.15.0-100-generic```
/kind content
/area blog
Correction in the blog text, which allows to avoid the error of mismatch between the kernel version for which the probe was compiled and the kernel version that's currently running on your system.
n/a
Fixes #
see https://kubernetes.slack.com/archives/CMWH3EH32/p1701096740993579
> Update falco-m1.md, use modern-bpf for helm

- data/en/reference/daemon/config_options.yaml
/kind cleanup
As per the following PRs:
* syscall_buf_size_preset https://github.com/falcosecurity/falco/pull/3087
* outputs https://github.com/falcosecurity/falco/pull/2841 
* metadata_download this https://github.com/falcosecurity/falco/pull/2914
Fixes #1193
> update(content): remove old config options from documentation page

- content/en/docs/metrics/falco-metrics.md
> /kind bug
> /kind design
/kind content
> /kind event
> /area blog
Explain how to activate the /metrics endpoint and what it will return.
Fixes #1291
> chore: add new Prometheus endpoint information

- content/en/docs/metrics/falco-metrics.md
> /kind bug
/kind cleanup
> /kind design
> /kind event
> /area blog
Improve prometheus and plugin metrics info, see https://github.com/falcosecurity/falco/issues/3229
@sgaist would you mind helping with the review? Thank you!
@sboschman are these updates ok? Do you have additional input?
CC @Issif 
Fixes #
> cleanup(metrics): improve prometheus and plugin metrics info

- content/en/docs/metrics/falco-metrics.md
- content/en/docs/reference/plugins/plugin-api-reference.md
> /kind bug
> /kind design
/kind content
> /kind event
> /area blog
Updates the plugin API reference to version 3.6.0.
Updates docs about enabling plugin metrics in Falco.
Fixes #
Please note that this documents features available in Falco 0.38.1, so it should be merged after the Falco release.
> update: plugin API reference to version 3.6.0

- content/en/blog/gsoc2023-week2/index.md
- content/en/blog/gsoc2023/index.md
> /kind bug
> /kind design
/kind content
> /kind event
/area blog
Fixes #
> Fix: Corrected typos in gsoc-blog

- content/en/docs/outputs/forwarding.md
> Fix Policy report link

- config/_default/params.toml
- data/training/offerings/detect-cryptomining.yaml
- data/training/offerings/falco-101.yaml
- data/training/offerings/falco-plugins.yaml
This updates the links for the Sysdig training content. The old links were removed since we switched to a different training platform.
/kind content
> fix: update sysdig training links

- content/en/docs/reference/rules/default-rules/index.md
/kind bug
See: https://github.com/falcosecurity/falco/issues/3296
Fixes #
> fix(docs): update rules setup documentation

- content/en/docs/setup/tarball.md
> /kind bug
> /kind design
/kind content
> /kind event
> /area blog
This PR fixes the command used in the documentation to retrieve the Falco pid for hot reloading.
Fixes #
> fix(docs): fix command to retrieve Falco pid for hot reloading

- content/en/docs/rules/overriding.md
> /kind bug
/kind cleanup
> /kind design
/kind content
> /kind event
> /area blog
This PR rephrases the rule overriding documentation by putting more emphasis on `append` key deprecation. Moving in this direction, the operator precedence section has been moved before sections documenting the deprecated feature.
Fixes #
> update(docs): rephrase and update rule override doc

- content/en/blog/falco-0-39-0/index.md
- content/en/docs/outputs/formatting.md
/kind bug
/area blog
Sadly, the `-o` parsing that allows you to say something like `-o 'append_output[]={"match": {"source": "syscall"}, "extra_fields": ["evt.hostname"], "extra_output": "on CPU %evt.cpu"}'` has a bug and I noticed after release 🤦 . I'm fixing the issue but will need to remove references to it from the docs until a patch release.
Fixes #
> fix(docs): remove references to broken -o variant

- content/en/docs/reference/daemon/cli-arguments/cli-arguments.md
- content/en/docs/setup/enviroments.md
- content/en/docs/troubleshooting/missing-fields.md
> /kind bug
> /kind design
/kind content
> /kind event
> /area blog
This PR replaces the references to `--cri` and `--disable-cri-async` cri-related options in the documentation. Moreover, it updates the Falco CLI arguments page. The deprecated options are left into the CLI arguments page to be consistent with the later published Falco 0.39.1 version.
Fixes #1378
> update(docs): replace deprecated cri options and update falco cli arguments page

- content/en/docs/setup/packages.md
Mention the addition of falco.service systemd alias to the main services falco-bpf.service, falco-custom.service and falco-modern-bpf.service.
> /kind bug
> /kind design
/kind content
> /kind event
> /area blog
This PR reflects the addition of `falco.service` systemd alias to main services `falco-bpf.service`, `falco-custom.service` and `falco-modern-bpf.service` in the documentation.
Fixes #1376
> update(docs): update systemd-related doc for Falco 0.39.1

- content/en/docs/reference/plugins/plugin-api-reference.md
A bunch of functions didn't have a plugin_ prefix. Added.
/kind bug
> /kind design
> /kind event
> /area blog
Update plugin documentation to add a bunch of missing plugin_ prefixes.
Fixes #
> Update plugin docs, add missing "plugin_" prefixes

- .github/workflows/links.yml
- content/en/blog/atomic-red-falco/index.md
- content/en/blog/falcosidekick-2-29-0/index.md
- content/en/docs/_index.md
- content/en/docs/concepts/event-sources/plugins/_index.md
- content/en/docs/developer-guide/grpc/_index.md
- content/en/docs/getting-started/kubernetes-quickstart.md
- content/en/docs/metrics/performance.md
- content/en/docs/setup/container.md
- content/en/docs/setup/kubernetes.md
- content/en/docs/setup/packages.md
- content/en/docs/setup/tarball.md
> /kind bug
/kind cleanup
> /kind design
/kind content
> /kind event
/area blog
This PR fixes all broken links (404 errors) between the different pages + introduces a new CI job to check the links at every PR to avoid to introduce new broken links
Fixes #
This PR reproduces the same CI Job we have for the charts https://github.com/falcosecurity/charts/blob/master/.github/workflows/links.yml
> fix 404 broken links + add a workflow to checks the links

- content/en/docs/setup/container.md
- content/en/docs/setup/download.md
> /kind bug
> /kind design
/kind content
> /kind event
> /area blog
See https://github.com/falcosecurity/falco/issues/3165 and https://github.com/falcosecurity/falco/pull/3273
Fixes #
/hold until Falco 0.40 is out
> update docker images usage for Falco 0.40

- content/en/docs/reference/rules/examples/write_binary_dir.md
The 'write_binary_dir' rule's condition refers to 'package_mgmt_binaries' as it would be a list of strings when it is actually a macro. The solution is to refer to it as a macro, which fixes the warning and also enables the intended behavior.
/kind content
/area rules
The original example produces a warning and does not behave as expected: binaries defined by 'package_mgmt_binaries' are not excluded.
Fixes #1464 
> Fix the rule example defined in write_binary_dir.md

- content/en/docs/developer-guide/grpc/_index.md
/kind cleanup
While reading this documentation, I noticed a broken link.
This updates the link to match the links in the sidebar.
> Fix broken Golang SDK link
